const premiumPlan = { label: "Premium", monthly: 12, prefix: "NSP-PREMIUM" };
const languageStorageKey = "novasentinel_premium_language";

const premiumFeatures = [
  "premium_updates",
  "beta_channel",
  "local_ioc_lookup",
  "post_alert_context",
];

const translations = {
  fr: {
    "meta.description": "NovaSentinel Premium: défense Windows complémentaire, licences professionnelles, réputation hash, règles signées et Admin Console téléchargeable.",
    "nav.aria": "Navigation principale",
    "nav.download": "Download",
    "nav.premium": "Premium",
    "nav.buy": "Acheter",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Sécurité",
    "language.label": "Langue",
    "language.aria": "Langue du site",
    "hero.eyebrow": "Défense Windows complémentaire",
    "hero.body": "Une application de protection explicable pour Windows, avec services Premium hébergés par NovaSentinel: licences, mises à jour signées, réputation hash et distribution professionnelle.",
    "download.aria": "Téléchargement NovaSentinel",
    "download.title": "Télécharger NovaSentinel",
    "download.body": "Version Windows avec activation Premium optionnelle",
    "download.button": "Download",
    "trust.aria": "Modèle de confiance",
    "trust.one.title": "Pas un EDR",
    "trust.one.body": "Pas de promesse kernel ou mini-filter.",
    "trust.two.title": "Hash first",
    "trust.two.body": "Pas d'upload de fichiers par défaut.",
    "trust.three.title": "Clé signée",
    "trust.three.body": "Droits Premium vérifiés localement.",
    "trust.four.title": "Admin local",
    "trust.four.body": "Le parc client reste chez le client.",
    "premium.eyebrow": "Ce que nous hébergeons",
    "premium.title": "Premium ajoute des services professionnels, pas un faux moteur antivirus.",
    "premium.body": "NovaSentinel reste une défense complémentaire. Le cloud NovaSentinel sert aux licences, règles signées, réputation par hash, mises à jour, achat et distribution.",
    "feature.rules.title": "Règles et IOC signés",
    "feature.rules.body": "Base de hashs/signatures, seuils heuristiques enrichis et listes d'IOC distribués en packs signés.",
    "feature.cloud.title": "Réputation cloud",
    "feature.cloud.body": "Vérification des hashs inconnus, score serveur privé, cache local et mode confidentialité.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "Rapports PDF/HTML, timeline d'incident, exports JSON/CSV et preuves enrichies.",
    "feature.distribution.title": "Distribution pro",
    "feature.distribution.body": "Auto-update de l'application, canal stable/beta, documentation pro et support prioritaire.",
    "buy.eyebrow": "Achat de clé",
    "buy.title": "Choisissez le nombre de postes et générez une clé Premium.",
    "buy.body": "Paiement s?curis? via Stripe Checkout. Votre licence Premium sera pr?par?e apr?s confirmation du paiement.",
    "form.org": "Organisation",
    "form.email": "Email responsable",
    "form.plan": "Plan",
    "form.plan_body": "Toutes les options Premium, facturées selon le nombre de postes.",
    "form.seats": "Nombre de postes",
    "form.submit": "Continuer avec Stripe",
    "summary.title": "Résumé",
    "summary.plan": "Plan",
    "summary.seats": "Postes",
    "summary.price": "Total mensuel",
    "summary.pending": "Clé générée après validation achat",
    "summary.note": "Stripe Checkout gérera le paiement. Votre clé Premium sera préparée après confirmation.",
    "checkout.created": "Session Stripe créée",
    "checkout.issued": "cl? confirm?e apr?s paiement",
    "admin.eyebrow": "Pour responsables de parc",
    "admin.title": "NovaSentinel Admin Console est téléchargeable.",
    "admin.body": "Nous hébergeons l'achat, les licences, les signatures et les mises à jour. L'Admin Console se télécharge côté client pour préparer les déploiements de masse, les clés Premium et les paquets de préconfiguration.",
    "admin.download": "Télécharger Admin Console",
    "admin.prepare": "Voir le paquet de préconfiguration",
    "admin.integration": "Intégration active",
    "admin.item1": "Import de la clé organisation achetée.",
    "admin.item2": "Génération de scripts GPO, Intune, RMM et PowerShell.",
    "admin.item3": "Paquets JSON de préconfiguration et modèle CSV licences.",
    "admin.item4": "Synchronisation optionnelle avec l'API licence NovaSentinel.",
    "admin.droits Premium": "Aper?u de configuration",
    "security.eyebrow": "Architecture sécurisée",
    "security.title": "Le secret reste côté NovaSentinel. L'app ne vérifie que des preuves signées.",
    "security.step1": "Achat et création de licence sur notre site.",
    "security.step2": "Activation par clé client ou clé organisation.",
    "security.step3": "NovaSentinel confirme les droits Premium de fa?on s?curis?e.",
    "security.step4": "L'app déverrouille seulement les droits signés et non expirés.",
    "footer.buy": "Acheter une clé",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Download",
  },
  en: {
    "meta.description": "NovaSentinel Premium: complementary Windows defense, professional licensing, hash reputation, signed rules, and downloadable Admin Console.",
    "nav.aria": "Main navigation",
    "nav.download": "Download",
    "nav.premium": "Premium",
    "nav.buy": "Buy",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Security",
    "language.label": "Language",
    "language.aria": "Site language",
    "hero.eyebrow": "Complementary Windows defense",
    "hero.body": "An explainable Windows protection app with NovaSentinel-hosted Premium services: licensing, signed updates, hash reputation, and professional distribution.",
    "download.aria": "NovaSentinel download",
    "download.title": "Download NovaSentinel",
    "download.body": "Windows version with optional Premium activation",
    "download.button": "Download",
    "trust.aria": "Trust model",
    "trust.one.title": "Not an EDR",
    "trust.one.body": "No kernel or mini-filter promise.",
    "trust.two.title": "Hash first",
    "trust.two.body": "No file upload by default.",
    "trust.three.title": "Signed key",
    "trust.three.body": "Premium rights verified locally.",
    "trust.four.title": "Local admin",
    "trust.four.body": "The customer fleet stays with the customer.",
    "premium.eyebrow": "What we host",
    "premium.title": "Premium adds professional services, not a fake antivirus engine.",
    "premium.body": "NovaSentinel remains a complementary defense. NovaSentinel Cloud handles licensing, signed rules, hash reputation, updates, purchase, and distribution.",
    "feature.rules.title": "Signed rules and IOCs",
    "feature.rules.body": "Hash/signature base, enriched heuristic thresholds, and IOC lists distributed as signed packs.",
    "feature.cloud.title": "Cloud reputation",
    "feature.cloud.body": "Unknown hash checks, private server score, local cache, and privacy mode.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "PDF/HTML reports, incident timeline, JSON/CSV exports, and enriched evidence.",
    "feature.distribution.title": "Pro distribution",
    "feature.distribution.body": "App auto-update, stable/beta channel, pro documentation, and priority support.",
    "buy.eyebrow": "Key purchase",
    "buy.title": "Choose the seat count and generate a Premium key.",
    "buy.body": "Secure payment through Stripe Checkout. Your Premium license will be prepared after payment confirmation.",
    "form.org": "Organization",
    "form.email": "IT contact email",
    "form.plan": "Plan",
    "form.plan_body": "All Premium options, billed by seat count.",
    "form.seats": "Seat count",
    "form.submit": "Continue with Stripe",
    "summary.title": "Summary",
    "summary.plan": "Plan",
    "summary.seats": "Seats",
    "summary.price": "Monthly total",
    "summary.pending": "Key generated after purchase validation",
    "summary.note": "Stripe Checkout will handle payment. Your Premium key will be prepared after confirmation.",
    "checkout.created": "Stripe session created",
    "checkout.issued": "key confirmed after payment",
    "admin.eyebrow": "For fleet managers",
    "admin.title": "NovaSentinel Admin Console is downloadable.",
    "admin.body": "We host purchase, licensing, signatures, and updates. The Admin Console is downloaded on the customer side to prepare mass deployments, Premium keys, and preconfiguration packages.",
    "admin.download": "Download Admin Console",
    "admin.prepare": "Preview preconfiguration package",
    "admin.integration": "Active integration",
    "admin.item1": "Import the purchased organization key.",
    "admin.item2": "Generate GPO, Intune, RMM, and PowerShell scripts.",
    "admin.item3": "JSON preconfiguration packages and license CSV template.",
    "admin.item4": "Optional sync with the NovaSentinel license API.",
    "admin.droits Premium": "Configuration preview",
    "security.eyebrow": "Secure architecture",
    "security.title": "The secret stays on NovaSentinel's side. The app only verifies signed proofs.",
    "security.step1": "Purchase and license creation on our site.",
    "security.step2": "Activation by customer key or organization key.",
    "security.step3": "NovaSentinel securely confirms Premium rights.",
    "security.step4": "The app unlocks only signed, non-expired rights.",
    "footer.buy": "Buy a key",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Download",
  },
  es: {
    "meta.description": "NovaSentinel Premium: defensa complementaria para Windows, licencias profesionales, reputación de hash, reglas firmadas y Admin Console descargable.",
    "nav.aria": "Navegación principal",
    "nav.download": "Descargar",
    "nav.premium": "Premium",
    "nav.buy": "Comprar",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Seguridad",
    "language.label": "Idioma",
    "language.aria": "Idioma del sitio",
    "hero.eyebrow": "Defensa complementaria para Windows",
    "hero.body": "Una aplicación de protección explicable para Windows con servicios Premium alojados por NovaSentinel: licencias, actualizaciones firmadas, reputación de hash y distribución profesional.",
    "download.aria": "Descarga de NovaSentinel",
    "download.title": "Descargar NovaSentinel",
    "download.body": "Versión Windows con activación Premium opcional",
    "download.button": "Descargar",
    "trust.aria": "Modelo de confianza",
    "trust.one.title": "No es un EDR",
    "trust.one.body": "Sin promesa de kernel ni mini-filter.",
    "trust.two.title": "Hash primero",
    "trust.two.body": "Sin subida de archivos por defecto.",
    "trust.three.title": "Clave firmada",
    "trust.three.body": "Derechos Premium verificados localmente.",
    "trust.four.title": "Admin local",
    "trust.four.body": "El parque del cliente permanece con el cliente.",
    "premium.eyebrow": "Lo que alojamos",
    "premium.title": "Premium añade servicios profesionales, no un motor antivirus falso.",
    "premium.body": "NovaSentinel sigue siendo una defensa complementaria. NovaSentinel Cloud gestiona licencias, reglas firmadas, reputación por hash, actualizaciones, compra y distribución.",
    "feature.rules.title": "Reglas e IOC firmados",
    "feature.rules.body": "Base de hashes/firmas, umbrales heurísticos enriquecidos y listas IOC distribuidas en paquetes firmados.",
    "feature.cloud.title": "Reputación cloud",
    "feature.cloud.body": "Verificación de hashes desconocidos, puntuación privada del servidor, caché local y modo privacidad.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "Informes PDF/HTML, timeline de incidente, exportaciones JSON/CSV y evidencias enriquecidas.",
    "feature.distribution.title": "Distribución pro",
    "feature.distribution.body": "Auto-update de la aplicación, canal stable/beta, documentación pro y soporte prioritario.",
    "buy.eyebrow": "Compra de clave",
    "buy.title": "Elige el número de puestos y genera una clave Premium.",
    "buy.body": "Pago seguro mediante Stripe Checkout. Tu licencia Premium se preparar? tras confirmar el pago.",
    "form.org": "Organización",
    "form.email": "Email responsable",
    "form.plan": "Plan",
    "form.plan_body": "Todas las opciones Premium, facturadas según el número de puestos.",
    "form.seats": "Número de puestos",
    "form.submit": "Continuar con Stripe",
    "summary.title": "Resumen",
    "summary.plan": "Plan",
    "summary.seats": "Puestos",
    "summary.price": "Total mensual",
    "summary.pending": "Clave generada tras validar la compra",
    "summary.note": "Stripe Checkout gestionará el pago. Tu clave Premium se preparará tras la confirmación.",
    "checkout.created": "Sesión Stripe creada",
    "checkout.issued": "clave confirmada tras el pago",
    "admin.eyebrow": "Para responsables de parque",
    "admin.title": "NovaSentinel Admin Console ya se puede descargar.",
    "admin.body": "Alojamos la compra, licencias, firmas y actualizaciones. La Admin Console se descarga en el cliente para preparar despliegues masivos, claves Premium y paquetes de preconfiguración.",
    "admin.download": "Descargar Admin Console",
    "admin.prepare": "Ver paquete de preconfiguración",
    "admin.integration": "Integración activa",
    "admin.item1": "Importar la clave de organización comprada.",
    "admin.item2": "Generar scripts GPO, Intune, RMM y PowerShell.",
    "admin.item3": "Paquetes JSON de preconfiguración y plantilla CSV de licencias.",
    "admin.item4": "Sincronización opcional con la API de licencias NovaSentinel.",
    "admin.droits Premium": "Vista previa de configuraci?n",
    "security.eyebrow": "Arquitectura segura",
    "security.title": "El secreto queda del lado de NovaSentinel. La app solo verifica pruebas firmadas.",
    "security.step1": "Compra y creación de licencia en nuestro sitio.",
    "security.step2": "Activación por clave de cliente o clave de organización.",
    "security.step3": "NovaSentinel confirma de forma segura los derechos Premium.",
    "security.step4": "La app desbloquea solo derechos firmados y no expirados.",
    "footer.buy": "Comprar una clave",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Descargar",
  },
  de: {
    "meta.description": "NovaSentinel Premium: ergänzende Windows-Verteidigung, professionelle Lizenzen, Hash-Reputation, signierte Regeln und herunterladbare Admin Console.",
    "nav.aria": "Hauptnavigation",
    "nav.download": "Download",
    "nav.premium": "Premium",
    "nav.buy": "Kaufen",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Sicherheit",
    "language.label": "Sprache",
    "language.aria": "Sprache der Website",
    "hero.eyebrow": "Ergänzende Windows-Verteidigung",
    "hero.body": "Eine erklärbare Windows-Schutz-App mit von NovaSentinel gehosteten Premium-Diensten: Lizenzen, signierte Updates, Hash-Reputation und professionelle Verteilung.",
    "download.aria": "NovaSentinel Download",
    "download.title": "NovaSentinel herunterladen",
    "download.body": "Windows-Version mit optionaler Premium-Aktivierung",
    "download.button": "Download",
    "trust.aria": "Vertrauensmodell",
    "trust.one.title": "Kein EDR",
    "trust.one.body": "Keine Kernel- oder Mini-Filter-Zusage.",
    "trust.two.title": "Hash first",
    "trust.two.body": "Standardmäßig kein Datei-Upload.",
    "trust.three.title": "Signierter Schlüssel",
    "trust.three.body": "Premium-Rechte werden lokal geprüft.",
    "trust.four.title": "Lokale Admins",
    "trust.four.body": "Die Kundenflotte bleibt beim Kunden.",
    "premium.eyebrow": "Was wir hosten",
    "premium.title": "Premium ergänzt professionelle Dienste, keinen falschen Antivirus-Motor.",
    "premium.body": "NovaSentinel bleibt eine ergänzende Verteidigung. NovaSentinel Cloud verwaltet Lizenzen, signierte Regeln, Hash-Reputation, Updates, Kauf und Verteilung.",
    "feature.rules.title": "Signierte Regeln und IOCs",
    "feature.rules.body": "Hash-/Signaturbasis, erweiterte Heuristik-Schwellen und IOC-Listen als signierte Pakete.",
    "feature.cloud.title": "Cloud-Reputation",
    "feature.cloud.body": "Prüfung unbekannter Hashes, privater Server-Score, lokaler Cache und Datenschutzmodus.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "PDF/HTML-Berichte, Incident-Timeline, JSON/CSV-Exporte und angereicherte Nachweise.",
    "feature.distribution.title": "Pro-Verteilung",
    "feature.distribution.body": "App-Auto-Update, stable/beta Kanal, Pro-Dokumentation und priorisierter Support.",
    "buy.eyebrow": "Schlüsselkauf",
    "buy.title": "Wählen Sie die Anzahl der Plätze und generieren Sie einen Premium-Schlüssel.",
    "buy.body": "Sichere Zahlung ?ber Stripe Checkout. Ihre Premium-Lizenz wird nach der Zahlungsbest?tigung vorbereitet.",
    "form.org": "Organisation",
    "form.email": "IT-Kontakt-E-Mail",
    "form.plan": "Plan",
    "form.plan_body": "Alle Premium-Optionen, nach Anzahl der Plätze abgerechnet.",
    "form.seats": "Anzahl Plätze",
    "form.submit": "Weiter mit Stripe",
    "summary.title": "Zusammenfassung",
    "summary.plan": "Plan",
    "summary.seats": "Plätze",
    "summary.price": "Monatssumme",
    "summary.pending": "Schlüssel nach Kaufvalidierung generiert",
    "summary.note": "Stripe Checkout verarbeitet die Zahlung. Ihr Premium-Schlüssel wird nach der Bestätigung vorbereitet.",
    "checkout.created": "Stripe-Sitzung erstellt",
    "checkout.issued": "Schl?ssel nach Zahlung best?tigt",
    "admin.eyebrow": "Für Flottenverantwortliche",
    "admin.title": "NovaSentinel Admin Console ist herunterladbar.",
    "admin.body": "Wir hosten Kauf, Lizenzen, Signaturen und Updates. Die Admin Console wird beim Kunden heruntergeladen, um Massenbereitstellungen, Premium-Schlüssel und Vorkonfigurationspakete vorzubereiten.",
    "admin.download": "Admin Console herunterladen",
    "admin.prepare": "Vorkonfigurationspaket ansehen",
    "admin.integration": "Aktive Integration",
    "admin.item1": "Gekauften Organisationsschlüssel importieren.",
    "admin.item2": "GPO-, Intune-, RMM- und PowerShell-Skripte generieren.",
    "admin.item3": "JSON-Vorkonfigurationspakete und Lizenz-CSV-Vorlage.",
    "admin.item4": "Optionale Synchronisierung mit der NovaSentinel-Lizenz-API.",
    "admin.droits Premium": "Konfigurationsvorschau",
    "security.eyebrow": "Sichere Architektur",
    "security.title": "Das Geheimnis bleibt bei NovaSentinel. Die App prüft nur signierte Nachweise.",
    "security.step1": "Kauf und Lizenzerstellung auf unserer Website.",
    "security.step2": "Aktivierung per Kundenschlüssel oder Organisationsschlüssel.",
    "security.step3": "NovaSentinel best?tigt Premium-Rechte sicher.",
    "security.step4": "Die App entsperrt nur signierte, nicht abgelaufene Rechte.",
    "footer.buy": "Schlüssel kaufen",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Download",
  },
  it: {
    "meta.description": "NovaSentinel Premium: difesa Windows complementare, licenze professionali, reputazione hash, regole firmate e Admin Console scaricabile.",
    "nav.aria": "Navigazione principale",
    "nav.download": "Download",
    "nav.premium": "Premium",
    "nav.buy": "Acquista",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Sicurezza",
    "language.label": "Lingua",
    "language.aria": "Lingua del sito",
    "hero.eyebrow": "Difesa Windows complementare",
    "hero.body": "Un'app di protezione spiegabile per Windows con servizi Premium ospitati da NovaSentinel: licenze, aggiornamenti firmati, reputazione hash e distribuzione professionale.",
    "download.aria": "Download NovaSentinel",
    "download.title": "Scarica NovaSentinel",
    "download.body": "Versione Windows con attivazione Premium opzionale",
    "download.button": "Download",
    "trust.aria": "Modello di fiducia",
    "trust.one.title": "Non è un EDR",
    "trust.one.body": "Nessuna promessa kernel o mini-filter.",
    "trust.two.title": "Hash first",
    "trust.two.body": "Nessun upload di file per impostazione predefinita.",
    "trust.three.title": "Chiave firmata",
    "trust.three.body": "Diritti Premium verificati localmente.",
    "trust.four.title": "Admin locale",
    "trust.four.body": "Il parco del cliente resta presso il cliente.",
    "premium.eyebrow": "Cosa ospitiamo",
    "premium.title": "Premium aggiunge servizi professionali, non un falso motore antivirus.",
    "premium.body": "NovaSentinel resta una difesa complementare. NovaSentinel Cloud gestisce licenze, regole firmate, reputazione hash, aggiornamenti, acquisto e distribuzione.",
    "feature.rules.title": "Regole e IOC firmati",
    "feature.rules.body": "Base hash/firme, soglie euristiche arricchite e liste IOC distribuite in pacchetti firmati.",
    "feature.cloud.title": "Reputazione cloud",
    "feature.cloud.body": "Verifica degli hash sconosciuti, punteggio server privato, cache locale e modalità privacy.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "Report PDF/HTML, timeline incidente, export JSON/CSV e prove arricchite.",
    "feature.distribution.title": "Distribuzione pro",
    "feature.distribution.body": "Auto-update dell'app, canale stable/beta, documentazione pro e supporto prioritario.",
    "buy.eyebrow": "Acquisto chiave",
    "buy.title": "Scegli il numero di postazioni e genera una chiave Premium.",
    "buy.body": "Pagamento sicuro tramite Stripe Checkout. La tua licenza Premium sar? preparata dopo la conferma del pagamento.",
    "form.org": "Organizzazione",
    "form.email": "Email responsabile",
    "form.plan": "Piano",
    "form.plan_body": "Tutte le opzioni Premium, fatturate in base al numero di postazioni.",
    "form.seats": "Numero postazioni",
    "form.submit": "Continua con Stripe",
    "summary.title": "Riepilogo",
    "summary.plan": "Piano",
    "summary.seats": "Postazioni",
    "summary.price": "Totale mensile",
    "summary.pending": "Chiave generata dopo la validazione dell'acquisto",
    "summary.note": "Stripe Checkout gestirà il pagamento. La chiave Premium sarà preparata dopo la conferma.",
    "checkout.created": "Sessione Stripe creata",
    "checkout.issued": "chiave confermata dopo il pagamento",
    "admin.eyebrow": "Per responsabili di parco",
    "admin.title": "NovaSentinel Admin Console è scaricabile.",
    "admin.body": "Ospitiamo acquisto, licenze, firme e aggiornamenti. L'Admin Console viene scaricata dal cliente per preparare distribuzioni massive, chiavi Premium e pacchetti di preconfigurazione.",
    "admin.download": "Scarica Admin Console",
    "admin.prepare": "Vedi pacchetto di preconfigurazione",
    "admin.integration": "Integrazione attiva",
    "admin.item1": "Import della chiave organizzazione acquistata.",
    "admin.item2": "Generazione di script GPO, Intune, RMM e PowerShell.",
    "admin.item3": "Pacchetti JSON di preconfigurazione e modello CSV licenze.",
    "admin.item4": "Sincronizzazione opzionale con l'API licenze NovaSentinel.",
    "admin.droits Premium": "Anteprima configurazione",
    "security.eyebrow": "Architettura sicura",
    "security.title": "Il segreto resta lato NovaSentinel. L'app verifica solo prove firmate.",
    "security.step1": "Acquisto e creazione licenza sul nostro sito.",
    "security.step2": "Attivazione con chiave cliente o chiave organizzazione.",
    "security.step3": "NovaSentinel conferma in modo sicuro i diritti Premium.",
    "security.step4": "L'app sblocca solo diritti firmati e non scaduti.",
    "footer.buy": "Acquista una chiave",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Download",
  },
  pt: {
    "meta.description": "NovaSentinel Premium: defesa Windows complementar, licenças profissionais, reputação hash, regras assinadas e Admin Console transferível.",
    "nav.aria": "Navegação principal",
    "nav.download": "Download",
    "nav.premium": "Premium",
    "nav.buy": "Comprar",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Segurança",
    "language.label": "Idioma",
    "language.aria": "Idioma do site",
    "hero.eyebrow": "Defesa Windows complementar",
    "hero.body": "Uma aplicação de proteção explicável para Windows com serviços Premium alojados pela NovaSentinel: licenças, atualizações assinadas, reputação hash e distribuição profissional.",
    "download.aria": "Download NovaSentinel",
    "download.title": "Transferir NovaSentinel",
    "download.body": "Versão Windows com ativação Premium opcional",
    "download.button": "Download",
    "trust.aria": "Modelo de confiança",
    "trust.one.title": "Não é um EDR",
    "trust.one.body": "Sem promessa kernel ou mini-filter.",
    "trust.two.title": "Hash first",
    "trust.two.body": "Sem upload de ficheiros por defeito.",
    "trust.three.title": "Chave assinada",
    "trust.three.body": "Direitos Premium verificados localmente.",
    "trust.four.title": "Admin local",
    "trust.four.body": "O parque do cliente fica no cliente.",
    "premium.eyebrow": "O que alojamos",
    "premium.title": "Premium adiciona serviços profissionais, não um falso motor antivírus.",
    "premium.body": "NovaSentinel continua a ser uma defesa complementar. O NovaSentinel Cloud gere licenças, regras assinadas, reputação por hash, atualizações, compra e distribuição.",
    "feature.rules.title": "Regras e IOC assinados",
    "feature.rules.body": "Base de hashes/assinaturas, limites heurísticos enriquecidos e listas IOC distribuídas em pacotes assinados.",
    "feature.cloud.title": "Reputação cloud",
    "feature.cloud.body": "Verificação de hashes desconhecidos, pontuação de servidor privado, cache local e modo privacidade.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "Relatórios PDF/HTML, timeline de incidente, exportações JSON/CSV e provas enriquecidas.",
    "feature.distribution.title": "Distribuição pro",
    "feature.distribution.body": "Auto-update da aplicação, canal stable/beta, documentação pro e suporte prioritário.",
    "buy.eyebrow": "Compra de chave",
    "buy.title": "Escolha o número de postos e gere uma chave Premium.",
    "buy.body": "Pagamento seguro via Stripe Checkout. A sua licen?a Premium ser? preparada ap?s a confirma??o do pagamento.",
    "form.org": "Organização",
    "form.email": "Email responsável",
    "form.plan": "Plano",
    "form.plan_body": "Todas as opções Premium, faturadas pelo número de postos.",
    "form.seats": "Número de postos",
    "form.submit": "Continuar com Stripe",
    "summary.title": "Resumo",
    "summary.plan": "Plano",
    "summary.seats": "Postos",
    "summary.price": "Total mensal",
    "summary.pending": "Chave gerada após validação da compra",
    "summary.note": "Stripe Checkout vai gerir o pagamento. A chave Premium será preparada após confirmação.",
    "checkout.created": "Sessão Stripe criada",
    "checkout.issued": "chave confirmada ap?s pagamento",
    "admin.eyebrow": "Para responsáveis de parque",
    "admin.title": "NovaSentinel Admin Console está disponível para transferência.",
    "admin.body": "Alojamos compra, licenças, assinaturas e atualizações. A Admin Console é transferida no cliente para preparar implantações em massa, chaves Premium e pacotes de pré-configuração.",
    "admin.download": "Transferir Admin Console",
    "admin.prepare": "Ver pacote de pré-configuração",
    "admin.integration": "Integração ativa",
    "admin.item1": "Importar a chave de organização comprada.",
    "admin.item2": "Gerar scripts GPO, Intune, RMM e PowerShell.",
    "admin.item3": "Pacotes JSON de pré-configuração e modelo CSV de licenças.",
    "admin.item4": "Sincronização opcional com a API de licenças NovaSentinel.",
    "admin.droits Premium": "Pr?-visualiza??o da configura??o",
    "security.eyebrow": "Arquitetura segura",
    "security.title": "O segredo fica do lado da NovaSentinel. A app só verifica provas assinadas.",
    "security.step1": "Compra e criação de licença no nosso site.",
    "security.step2": "Ativação por chave cliente ou chave organização.",
    "security.step3": "A NovaSentinel confirma os direitos Premium de forma segura.",
    "security.step4": "A app desbloqueia apenas direitos assinados e não expirados.",
    "footer.buy": "Comprar uma chave",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Download",
  },
  ar: {
    "meta.description": "NovaSentinel Premium: دفاع Windows تكميلي، تراخيص احترافية، سمعة hash، قواعد موقعة و Admin Console قابلة للتنزيل.",
    "nav.aria": "التنقل الرئيسي",
    "nav.download": "تنزيل",
    "nav.premium": "Premium",
    "nav.buy": "شراء",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "الأمان",
    "language.label": "اللغة",
    "language.aria": "لغة الموقع",
    "hero.eyebrow": "دفاع Windows تكميلي",
    "hero.body": "تطبيق حماية قابل للشرح لـ Windows مع خدمات Premium مستضافة من NovaSentinel: التراخيص، التحديثات الموقعة، سمعة hash والتوزيع الاحترافي.",
    "download.aria": "تنزيل NovaSentinel",
    "download.title": "تنزيل NovaSentinel",
    "download.body": "إصدار Windows مع تفعيل Premium اختياري",
    "download.button": "تنزيل",
    "trust.aria": "نموذج الثقة",
    "trust.one.title": "ليس EDR",
    "trust.one.body": "لا وعود kernel أو mini-filter.",
    "trust.two.title": "Hash أولا",
    "trust.two.body": "لا رفع ملفات افتراضيا.",
    "trust.three.title": "مفتاح موقع",
    "trust.three.body": "حقوق Premium تتحقق محليا.",
    "trust.four.title": "إدارة محلية",
    "trust.four.body": "أجهزة العميل تبقى لدى العميل.",
    "premium.eyebrow": "ما نستضيفه",
    "premium.title": "Premium يضيف خدمات احترافية، وليس محرك مضاد فيروسات وهميا.",
    "premium.body": "يبقى NovaSentinel دفاعا تكميليا. NovaSentinel Cloud يدير التراخيص، القواعد الموقعة، سمعة hash، التحديثات، الشراء والتوزيع.",
    "feature.rules.title": "قواعد و IOC موقعة",
    "feature.rules.body": "قاعدة hashes/signatures وحدود heuristics محسنة وقوائم IOC موزعة كحزم موقعة.",
    "feature.cloud.title": "سمعة cloud",
    "feature.cloud.body": "فحص hashes غير المعروفة، نتيجة خادم خاص، cache محلي ووضع خصوصية.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "تقارير PDF/HTML، timeline للحادث، تصدير JSON/CSV وأدلة محسنة.",
    "feature.distribution.title": "توزيع احترافي",
    "feature.distribution.body": "تحديث تلقائي للتطبيق، قناة stable/beta، توثيق احترافي ودعم أولوية.",
    "buy.eyebrow": "شراء مفتاح",
    "buy.title": "اختر عدد الأجهزة وأنشئ مفتاح Premium.",
    "buy.body": "??? ??? ??? Stripe Checkout. ???? ????? ????? Premium ??? ????? ?????.",
    "form.org": "المؤسسة",
    "form.email": "بريد مسؤول IT",
    "form.plan": "الخطة",
    "form.plan_body": "كل خيارات Premium، مع فوترة حسب عدد الأجهزة.",
    "form.seats": "عدد الأجهزة",
    "form.submit": "المتابعة مع Stripe",
    "summary.title": "الملخص",
    "summary.plan": "الخطة",
    "summary.seats": "الأجهزة",
    "summary.price": "الإجمالي الشهري",
    "summary.pending": "يتم إنشاء المفتاح بعد تأكيد الشراء",
    "summary.note": "سيتولى Stripe Checkout الدفع. سيتم تجهيز مفتاح Premium بعد التأكيد.",
    "checkout.created": "تم إنشاء جلسة Stripe",
    "checkout.issued": "????? ???? ??? ?????",
    "admin.eyebrow": "لمسؤولي الأجهزة",
    "admin.title": "NovaSentinel Admin Console متاحة للتنزيل.",
    "admin.body": "نحن نستضيف الشراء والتراخيص والتوقيعات والتحديثات. يتم تنزيل Admin Console لدى العميل لتحضير النشر الجماعي ومفاتيح Premium وحزم التهيئة المسبقة.",
    "admin.download": "تنزيل Admin Console",
    "admin.prepare": "معاينة حزمة التهيئة المسبقة",
    "admin.integration": "تكامل نشط",
    "admin.item1": "استيراد مفتاح المؤسسة المشترى.",
    "admin.item2": "إنشاء scripts لـ GPO و Intune و RMM و PowerShell.",
    "admin.item3": "حزم JSON للتهيئة المسبقة وقالب CSV للتراخيص.",
    "admin.item4": "مزامنة اختيارية مع NovaSentinel license API.",
    "admin.droits Premium": "?????? ?????????",
    "security.eyebrow": "هندسة آمنة",
    "security.title": "يبقى السر لدى NovaSentinel. التطبيق يتحقق فقط من أدلة موقعة.",
    "security.step1": "الشراء وإنشاء الترخيص على موقعنا.",
    "security.step2": "التفعيل بمفتاح عميل أو مفتاح مؤسسة.",
    "security.step3": "???? NovaSentinel ???? Premium ???? ???.",
    "security.step4": "يفتح التطبيق فقط الحقوق الموقعة وغير المنتهية.",
    "footer.buy": "شراء مفتاح",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "تنزيل",
  },
};

const superadminTranslations = {
  fr: {
    "nav.superadmin": "Superadmin",
    "superadmin.eyebrow": "Interne NovaSentinel",
    "superadmin.title": "Dashboard Superadmin pour piloter Premium sans exposer les secrets.",
    "superadmin.body": "Espace r?serv? ? l??quipe NovaSentinel pour piloter les licences, les releases et les op?rations Premium.",
    "superadmin.nav_aria": "Navigation Superadmin",
    "superadmin.tab.overview": "Vue globale",
    "superadmin.tab.licenses": "Licences",
    "superadmin.tab.stripe": "Stripe",
    "superadmin.tab.security": "Sécurité",
    "superadmin.kpi.orgs": "Organisations",
    "superadmin.kpi.orgs_note": "clients Premium",
    "superadmin.kpi.seats": "Postes actifs",
    "superadmin.kpi.seats_note": "sur 5 600 achetés",
    "superadmin.kpi.mrr": "MRR estimé",
    "superadmin.kpi.mrr_note": "plan Premium unique",
    "superadmin.kpi.risk": "Alertes admin",
    "superadmin.kpi.risk_note": "à traiter",
    "superadmin.actions.title": "Actions sensibles",
    "superadmin.actions.revoke": "Révoquer une licence",
    "superadmin.actions.resign": "R?g?n?rer les droits Premium",
    "superadmin.actions.release": "Publier release stable",
    "superadmin.actions.audit": "Exporter l?historique",
    "superadmin.licenses.title": "Licences et organisations",
    "superadmin.status.active": "Actif",
    "superadmin.status.watch": "Surveillance",
    "superadmin.status.pending": "Paiement attendu",
    "superadmin.stripe.title": "Stripe et facturation",
    "superadmin.event.license_created": "licence créée",
    "superadmin.event.requires_action": "action requise",
    "superadmin.event.seats_updated": "postes mis à jour",
    "superadmin.security.title": "Garde-fous obligatoires",
    "superadmin.security.mfa": "MFA obligatoire pour tous les admins internes.",
    "superadmin.security.roles": "Rôles séparés : support, billing, release manager, superadmin.",
    "superadmin.security.keys": "Secrets critiques conserv?s dans un environnement prot?g?.",
    "superadmin.security.audit": "Historique conserv? pour chaque action sensible.",
    "superadmin.security.rate": "Alertes et protections sur les acc?s sensibles.",
  },
  en: {
    "nav.superadmin": "Superadmin",
    "superadmin.eyebrow": "NovaSentinel internal",
    "superadmin.title": "Superadmin dashboard to run Premium without exposing secrets.",
    "superadmin.body": "A NovaSentinel team area for managing licenses, releases, and Premium operations.",
    "superadmin.nav_aria": "Superadmin navigation",
    "superadmin.tab.overview": "Overview",
    "superadmin.tab.licenses": "Licenses",
    "superadmin.tab.stripe": "Stripe",
    "superadmin.tab.security": "Security",
    "superadmin.kpi.orgs": "Organizations",
    "superadmin.kpi.orgs_note": "Premium customers",
    "superadmin.kpi.seats": "Active seats",
    "superadmin.kpi.seats_note": "of 5,600 purchased",
    "superadmin.kpi.mrr": "Estimated MRR",
    "superadmin.kpi.mrr_note": "single Premium plan",
    "superadmin.kpi.risk": "Admin alerts",
    "superadmin.kpi.risk_note": "to handle",
    "superadmin.actions.title": "Sensitive actions",
    "superadmin.actions.revoke": "Revoke license",
    "superadmin.actions.resign": "Regenerate Premium rights",
    "superadmin.actions.release": "Publish stable release",
    "superadmin.actions.audit": "Export history",
    "superadmin.licenses.title": "Licenses and organizations",
    "superadmin.status.active": "Active",
    "superadmin.status.watch": "Watch",
    "superadmin.status.pending": "Payment pending",
    "superadmin.stripe.title": "Stripe and billing",
    "superadmin.event.license_created": "license created",
    "superadmin.event.requires_action": "action required",
    "superadmin.event.seats_updated": "seats updated",
    "superadmin.security.title": "Required guardrails",
    "superadmin.security.mfa": "MFA required for every internal admin.",
    "superadmin.security.roles": "Separate roles: support, billing, release manager, superadmin.",
    "superadmin.security.keys": "Critical secrets are kept in a protected environment.",
    "superadmin.security.audit": "History retained for every sensitive action.",
    "superadmin.security.rate": "Alerts and protections on sensitive access.",
  },
};

["es", "de", "it", "pt", "ar"].forEach((language) => {
  superadminTranslations[language] = { ...superadminTranslations.en };
});

Object.assign(superadminTranslations.es, {
  "superadmin.eyebrow": "Interno NovaSentinel",
  "superadmin.title": "Dashboard Superadmin para gestionar Premium sin exponer secretos.",
  "superadmin.body": "Espacio reservado al equipo NovaSentinel para gestionar licencias, versiones y operaciones Premium.",
  "superadmin.nav_aria": "Navegación Superadmin",
  "superadmin.tab.overview": "Vista global",
  "superadmin.tab.licenses": "Licencias",
  "superadmin.tab.security": "Seguridad",
  "superadmin.kpi.orgs": "Organizaciones",
  "superadmin.kpi.orgs_note": "clientes Premium",
  "superadmin.kpi.seats": "Puestos activos",
  "superadmin.kpi.seats_note": "de 5 600 comprados",
  "superadmin.kpi.mrr": "MRR estimado",
  "superadmin.kpi.mrr_note": "plan Premium único",
  "superadmin.kpi.risk": "Alertas admin",
  "superadmin.kpi.risk_note": "por tratar",
  "superadmin.actions.title": "Acciones sensibles",
  "superadmin.actions.revoke": "Revocar licencia",
  "superadmin.actions.resign": "Regenerar derechos Premium",
  "superadmin.actions.release": "Publicar release estable",
  "superadmin.actions.audit": "Exportar historial",
  "superadmin.licenses.title": "Licencias y organizaciones",
  "superadmin.status.active": "Activo",
  "superadmin.status.watch": "Vigilancia",
  "superadmin.status.pending": "Pago pendiente",
  "superadmin.stripe.title": "Stripe y facturación",
  "superadmin.event.license_created": "licencia creada",
  "superadmin.event.requires_action": "acción requerida",
  "superadmin.event.seats_updated": "puestos actualizados",
  "superadmin.security.title": "Guardrails obligatorios",
  "superadmin.security.mfa": "MFA obligatorio para todos los admins internos.",
  "superadmin.security.roles": "Roles separados: soporte, billing, release manager, superadmin.",
  "superadmin.security.keys": "Los secretos cr?ticos se conservan en un entorno protegido.",
  "superadmin.security.audit": "Historial conservado para cada acci?n sensible.",
  "superadmin.security.rate": "Alertas y protecciones en accesos sensibles.",
});

Object.assign(superadminTranslations.de, {
  "superadmin.eyebrow": "NovaSentinel intern",
  "superadmin.title": "Superadmin-Dashboard zur Steuerung von Premium ohne Offenlegung von Geheimnissen.",
  "superadmin.body": "Ein Bereich f?r das NovaSentinel-Team zur Verwaltung von Lizenzen, Releases und Premium-Abl?ufen.",
  "superadmin.nav_aria": "Superadmin-Navigation",
  "superadmin.tab.overview": "Übersicht",
  "superadmin.tab.licenses": "Lizenzen",
  "superadmin.tab.security": "Sicherheit",
  "superadmin.kpi.orgs": "Organisationen",
  "superadmin.kpi.orgs_note": "Premium-Kunden",
  "superadmin.kpi.seats": "Aktive Plätze",
  "superadmin.kpi.seats_note": "von 5.600 gekauft",
  "superadmin.kpi.mrr": "Geschätzter MRR",
  "superadmin.kpi.mrr_note": "einziger Premium-Plan",
  "superadmin.kpi.risk": "Admin-Warnungen",
  "superadmin.kpi.risk_note": "zu bearbeiten",
  "superadmin.actions.title": "Sensible Aktionen",
  "superadmin.actions.revoke": "Lizenz widerrufen",
  "superadmin.actions.resign": "Premium-Rechte erneuern",
  "superadmin.actions.release": "Stable Release veröffentlichen",
  "superadmin.actions.audit": "Historie exportieren",
  "superadmin.licenses.title": "Lizenzen und Organisationen",
  "superadmin.status.active": "Aktiv",
  "superadmin.status.watch": "Überwachung",
  "superadmin.status.pending": "Zahlung ausstehend",
  "superadmin.stripe.title": "Stripe und Abrechnung",
  "superadmin.event.license_created": "Lizenz erstellt",
  "superadmin.event.requires_action": "Aktion erforderlich",
  "superadmin.event.seats_updated": "Plätze aktualisiert",
  "superadmin.security.title": "Pflicht-Leitplanken",
  "superadmin.security.mfa": "MFA ist für alle internen Admins verpflichtend.",
  "superadmin.security.roles": "Getrennte Rollen: Support, Billing, Release Manager, Superadmin.",
  "superadmin.security.keys": "Kritische Secrets bleiben in einer gesch?tzten Umgebung.",
  "superadmin.security.audit": "Historie f?r sensible Aktionen wird aufbewahrt.",
  "superadmin.security.rate": "Warnungen und Schutz f?r sensible Zugriffe.",
});

Object.assign(superadminTranslations.it, {
  "superadmin.eyebrow": "Interno NovaSentinel",
  "superadmin.title": "Dashboard Superadmin per gestire Premium senza esporre segreti.",
  "superadmin.body": "Area riservata al team NovaSentinel per gestire licenze, release e operazioni Premium.",
  "superadmin.nav_aria": "Navigazione Superadmin",
  "superadmin.tab.overview": "Vista globale",
  "superadmin.tab.licenses": "Licenze",
  "superadmin.tab.security": "Sicurezza",
  "superadmin.kpi.orgs": "Organizzazioni",
  "superadmin.kpi.orgs_note": "clienti Premium",
  "superadmin.kpi.seats": "Postazioni attive",
  "superadmin.kpi.seats_note": "su 5.600 acquistate",
  "superadmin.kpi.mrr": "MRR stimato",
  "superadmin.kpi.mrr_note": "piano Premium unico",
  "superadmin.kpi.risk": "Avvisi admin",
  "superadmin.kpi.risk_note": "da gestire",
  "superadmin.actions.title": "Azioni sensibili",
  "superadmin.actions.revoke": "Revoca licenza",
  "superadmin.actions.resign": "Rigenera diritti Premium",
  "superadmin.actions.release": "Pubblica release stable",
  "superadmin.actions.audit": "Esporta cronologia",
  "superadmin.licenses.title": "Licenze e organizzazioni",
  "superadmin.status.active": "Attivo",
  "superadmin.status.watch": "Sorveglianza",
  "superadmin.status.pending": "Pagamento atteso",
  "superadmin.stripe.title": "Stripe e fatturazione",
  "superadmin.event.license_created": "licenza creata",
  "superadmin.event.requires_action": "azione richiesta",
  "superadmin.event.seats_updated": "postazioni aggiornate",
  "superadmin.security.title": "Garanzie obbligatorie",
  "superadmin.security.mfa": "MFA obbligatoria per tutti gli admin interni.",
  "superadmin.security.roles": "Ruoli separati: support, billing, release manager, superadmin.",
  "superadmin.security.keys": "I segreti critici restano in un ambiente protetto.",
  "superadmin.security.audit": "Cronologia conservata per ogni azione sensibile.",
  "superadmin.security.rate": "Avvisi e protezioni sugli accessi sensibili.",
});

Object.assign(superadminTranslations.pt, {
  "superadmin.eyebrow": "Interno NovaSentinel",
  "superadmin.title": "Dashboard Superadmin para gerir Premium sem expor segredos.",
  "superadmin.body": "?rea reservada ? equipa NovaSentinel para gerir licen?as, releases e opera??es Premium.",
  "superadmin.nav_aria": "Navegação Superadmin",
  "superadmin.tab.overview": "Visão global",
  "superadmin.tab.licenses": "Licenças",
  "superadmin.tab.security": "Segurança",
  "superadmin.kpi.orgs": "Organizações",
  "superadmin.kpi.orgs_note": "clientes Premium",
  "superadmin.kpi.seats": "Postos ativos",
  "superadmin.kpi.seats_note": "de 5 600 comprados",
  "superadmin.kpi.mrr": "MRR estimado",
  "superadmin.kpi.mrr_note": "plano Premium único",
  "superadmin.kpi.risk": "Alertas admin",
  "superadmin.kpi.risk_note": "a tratar",
  "superadmin.actions.title": "Ações sensíveis",
  "superadmin.actions.revoke": "Revogar licença",
  "superadmin.actions.resign": "Regenerar direitos Premium",
  "superadmin.actions.release": "Publicar release stable",
  "superadmin.actions.audit": "Exportar hist?rico",
  "superadmin.licenses.title": "Licenças e organizações",
  "superadmin.status.active": "Ativo",
  "superadmin.status.watch": "Vigilância",
  "superadmin.status.pending": "Pagamento pendente",
  "superadmin.stripe.title": "Stripe e faturação",
  "superadmin.event.license_created": "licença criada",
  "superadmin.event.requires_action": "ação necessária",
  "superadmin.event.seats_updated": "postos atualizados",
  "superadmin.security.title": "Proteções obrigatórias",
  "superadmin.security.mfa": "MFA obrigatório para todos os admins internos.",
  "superadmin.security.roles": "Papéis separados: suporte, billing, release manager, superadmin.",
  "superadmin.security.keys": "Os segredos cr?ticos ficam num ambiente protegido.",
  "superadmin.security.audit": "Hist?rico preservado para cada a??o sens?vel.",
  "superadmin.security.rate": "Alertas e prote??es nos acessos sens?veis.",
});

Object.assign(superadminTranslations.ar, {
  "nav.superadmin": "Superadmin",
  "superadmin.eyebrow": "داخلي NovaSentinel",
  "superadmin.title": "لوحة Superadmin لإدارة Premium دون كشف الأسرار.",
  "superadmin.body": "????? ????? ????? NovaSentinel ?????? ???????? ?????????? ??????? Premium.",
  "superadmin.nav_aria": "تنقل Superadmin",
  "superadmin.tab.overview": "نظرة عامة",
  "superadmin.tab.licenses": "التراخيص",
  "superadmin.tab.stripe": "Stripe",
  "superadmin.tab.security": "الأمان",
  "superadmin.kpi.orgs": "المؤسسات",
  "superadmin.kpi.orgs_note": "عملاء Premium",
  "superadmin.kpi.seats": "الأجهزة النشطة",
  "superadmin.kpi.seats_note": "من 5,600 مشتراة",
  "superadmin.kpi.mrr": "MRR تقديري",
  "superadmin.kpi.mrr_note": "خطة Premium واحدة",
  "superadmin.kpi.risk": "تنبيهات admin",
  "superadmin.kpi.risk_note": "قيد المعالجة",
  "superadmin.actions.title": "إجراءات حساسة",
  "superadmin.actions.revoke": "إلغاء ترخيص",
  "superadmin.actions.resign": "????? ????? ???? Premium",
  "superadmin.actions.release": "نشر release stable",
  "superadmin.actions.audit": "????? ?????",
  "superadmin.licenses.title": "التراخيص والمؤسسات",
  "superadmin.status.active": "نشط",
  "superadmin.status.watch": "مراقبة",
  "superadmin.status.pending": "دفع منتظر",
  "superadmin.stripe.title": "Stripe والفوترة",
  "superadmin.event.license_created": "تم إنشاء الترخيص",
  "superadmin.event.requires_action": "إجراء مطلوب",
  "superadmin.event.seats_updated": "تم تحديث الأجهزة",
  "superadmin.security.title": "ضوابط إلزامية",
  "superadmin.security.mfa": "MFA إلزامي لكل admins الداخليين.",
  "superadmin.security.roles": "أدوار منفصلة: support و billing و release manager و superadmin.",
  "superadmin.security.keys": "????? ??????? ??????? ?? ???? ?????.",
  "superadmin.security.audit": "??? ??? ??? ??? ????? ????.",
  "superadmin.security.rate": "??????? ?????? ?????? ??????.",
});

Object.entries(superadminTranslations).forEach(([language, values]) => {
  translations[language] = { ...translations[language], ...values };
});

Object.assign(translations.fr, {
  "meta.description": "NovaSentinel Premium : défense Windows complémentaire, licences professionnelles, réputation hash, règles signées et Admin Console téléchargeable.",
  "nav.download": "Télécharger",
  "nav.premium": "Premium",
  "nav.buy": "Acheter",
  "nav.admin": "Dashboard",
  "nav.login": "Login",
  "nav.security": "Sécurité",
  "language.label": "Langue",
  "hero.eyebrow": "Défense Windows complémentaire",
  "hero.body": "Une application de protection explicable pour Windows, avec services Premium hébergés par NovaSentinel : licences, mises à jour signées, réputation hash et distribution professionnelle.",
  "download.title": "Télécharger NovaSentinel",
  "download.body": "Version Windows avec activation Premium optionnelle",
  "download.button": "Download",
  "trust.one.title": "Pas un EDR",
  "trust.one.body": "Pas de promesse kernel ou mini-filter.",
  "trust.two.title": "Hash first",
  "trust.two.body": "Pas d'upload de fichiers par défaut.",
  "trust.three.title": "Clé signée",
  "trust.three.body": "Droits Premium vérifiés localement.",
  "trust.four.title": "Admin local",
  "trust.four.body": "Le parc client reste chez le client.",
  "premium.eyebrow": "Ce que nous hébergeons",
  "premium.title": "Premium ajoute des services professionnels, pas un faux moteur antivirus.",
  "premium.body": "NovaSentinel reste une défense complémentaire. Le cloud NovaSentinel sert aux licences, règles signées, réputation par hash, mises à jour, achat et distribution.",
  "feature.rules.title": "Règles et IOC signés",
  "feature.rules.body": "Base de hashs/signatures, seuils heuristiques enrichis et listes d'IOC distribués en packs signés.",
  "feature.cloud.title": "Réputation cloud",
  "feature.cloud.body": "Vérification des hashs inconnus, score serveur privé, cache local et mode confidentialité.",
  "feature.forensics.title": "Forensics Pro",
  "feature.forensics.body": "Rapports PDF/HTML, timeline d'incident, exports JSON/CSV et preuves enrichies.",
  "feature.distribution.title": "Distribution pro",
  "feature.distribution.body": "Auto-update de l'application, canal stable/beta, documentation pro et support prioritaire.",
  "buy.eyebrow": "Achat de clé",
  "buy.title": "Choisissez le nombre de postes et générez une clé Premium.",
  "buy.body": "Paiement s?curis? via Stripe Checkout. Votre licence Premium sera pr?par?e apr?s confirmation du paiement.",
  "form.org": "Organisation",
  "form.email": "Email responsable",
  "form.plan": "Plan",
  "form.plan_body": "Toutes les options Premium, facturées selon le nombre de postes.",
  "form.seats": "Nombre de postes",
  "form.submit": "Continuer avec Stripe",
  "summary.title": "Résumé",
  "summary.plan": "Plan",
  "summary.seats": "Postes",
  "summary.price": "Total mensuel",
  "summary.pending": "Clé générée après validation achat",
  "summary.note": "Stripe Checkout gère le paiement. Votre clé Premium sera préparée après confirmation.",
  "checkout.created": "Session Stripe créée",
  "checkout.issued": "cl? confirm?e apr?s paiement",
  "admin.eyebrow": "Pour responsables de parc",
  "admin.title": "NovaSentinel Admin Console est téléchargeable.",
  "admin.body": "Nous hébergeons l'achat, les licences, les signatures et les mises à jour. L'Admin Console se télécharge côté client pour préparer les déploiements de masse, les clés Premium et les paquets de préconfiguration.",
  "admin.download": "Télécharger Admin Console",
  "admin.prepare": "Voir le paquet de préconfiguration",
  "admin.integration": "Intégration active",
  "admin.item1": "Import de la clé organisation achetée.",
  "admin.item2": "Génération de scripts GPO, Intune, RMM et PowerShell.",
  "admin.item3": "Paquets JSON de préconfiguration et modèle CSV licences.",
  "admin.item4": "Synchronisation optionnelle avec l'API licence NovaSentinel.",
  "admin.droits Premium": "Aper?u de configuration",
  "security.eyebrow": "Architecture sécurisée",
  "security.title": "Le secret reste côté NovaSentinel. L'app ne vérifie que des preuves signées.",
  "security.step1": "Achat et création de licence sur notre site.",
  "security.step2": "Activation par clé client ou clé organisation.",
  "security.step3": "NovaSentinel confirme les droits Premium de fa?on s?curis?e.",
  "security.step4": "L'app déverrouille seulement les droits signés et non expirés.",
  "footer.buy": "Acheter une clé",
  "footer.admin": "Admin Console",
  "footer.login": "Login",
  "footer.download": "Download",
});

const clientFriendlyTranslations = {
  fr: {
    "meta.description": "NovaSentinel Premium : protection Windows complémentaire, licences professionnelles et outils de gestion pour les équipes IT.",
    "nav.download": "Télécharger",
    "nav.login": "Connexion",
    "hero.eyebrow": "Protection Windows complémentaire",
    "hero.body": "Une application claire pour renforcer la protection Windows, avec licences Premium, mises à jour de confiance et outils de gestion pour les équipes IT.",
    "trust.one.title": "Protection claire",
    "trust.one.body": "Des alertes compréhensibles et actionnables.",
    "trust.two.title": "Confidentialité",
    "trust.two.body": "Aucun fichier envoyé sans choix explicite.",
    "trust.three.title": "Accès vérifié",
    "trust.three.body": "Les options Premium se débloquent de façon sécurisée.",
    "trust.four.title": "Gestion locale",
    "trust.four.body": "Le parc informatique reste sous votre contrôle.",
    "premium.eyebrow": "Services Premium",
    "premium.title": "Premium ajoute les outils utiles aux équipes professionnelles.",
    "premium.body": "NovaSentinel Premium centralise l'achat, l'activation, les mises à jour et les outils de gestion, sans transformer l'application en antivirus lourd.",
    "feature.rules.title": "Règles de protection",
    "feature.rules.body": "Des packs de protection maintenus par NovaSentinel pour améliorer la détection locale.",
    "feature.cloud.title": "Réputation en ligne",
    "feature.cloud.body": "Une aide à la décision pour les éléments inconnus, avec un mode confidentialité par défaut.",
    "feature.forensics.title": "Rapports Pro",
    "feature.forensics.body": "Des rapports exploitables pour comprendre un incident et partager les constats.",
    "feature.distribution.title": "Distribution pro",
    "feature.distribution.body": "Mises à jour de l'application, canal stable ou beta, documentation pro et support prioritaire.",
    "buy.body": "Paiement sécurisé par Stripe. Votre licence Premium sera préparée après confirmation.",
    "form.submit": "Continuer vers le paiement",
    "summary.note": "Le paiement est sécurisé. Votre clé Premium sera préparée après confirmation.",
    "checkout.created": "Paiement prêt",
    "checkout.issued": "clé confirmée après paiement",
    "admin.body": "Nous gérons l'achat, les licences et les mises à jour. L'Admin Console aide les responsables IT à préparer un déploiement simple sur plusieurs postes.",
    "admin.prepare": "Voir l'aperçu",
    "admin.integration": "Prêt pour votre parc",
    "admin.item1": "Activation avec la clé organisation achetée.",
    "admin.item2": "Préparation guidée pour un déploiement en masse.",
    "admin.item3": "Suivi des postes et des licences utilisées.",
    "admin.item4": "Connexion optionnelle aux services Premium NovaSentinel.",
    "admin.droits Premium": "Aperçu de configuration",
    "security.eyebrow": "Sécurité",
    "security.title": "Les données sensibles restent protégées, l'application ne reçoit que le nécessaire.",
    "security.step3": "NovaSentinel confirme les droits Premium de façon sécurisée.",
    "security.step4": "L'application déverrouille uniquement les options autorisées.",
    "footer.login": "Connexion",
    "footer.download": "Télécharger",
    "nav.superadmin": "Console interne",
    "superadmin.title": "Console interne pour piloter NovaSentinel Premium.",
    "superadmin.nav_aria": "Navigation console interne",
    "superadmin.security.roles": "Accès séparés pour le support, la facturation et la publication.",
    "superadmin.security.keys": "Données sensibles conservées dans un environnement protégé.",
  },
  en: {
    "meta.description": "NovaSentinel Premium: complementary Windows protection, professional licensing, and management tools for IT teams.",
    "nav.download": "Download",
    "nav.login": "Sign in",
    "hero.eyebrow": "Complementary Windows protection",
    "hero.body": "A clear Windows protection app with Premium licensing, trusted updates, and management tools for IT teams.",
    "trust.one.title": "Clear protection",
    "trust.one.body": "Understandable alerts that lead to action.",
    "trust.two.title": "Privacy",
    "trust.two.body": "No file is sent without an explicit choice.",
    "trust.three.title": "Verified access",
    "trust.three.body": "Premium options unlock securely.",
    "trust.four.title": "Local control",
    "trust.four.body": "Your computer fleet stays under your control.",
    "premium.eyebrow": "Premium services",
    "premium.title": "Premium adds useful tools for professional teams.",
    "premium.body": "NovaSentinel Premium centralizes purchase, activation, updates, and management tools without turning the app into a heavy antivirus.",
    "feature.rules.title": "Protection rules",
    "feature.rules.body": "NovaSentinel-maintained protection packs improve local detection.",
    "feature.cloud.title": "Online reputation",
    "feature.cloud.body": "Decision support for unknown items, with privacy mode by default.",
    "feature.forensics.title": "Pro reports",
    "feature.forensics.body": "Actionable reports to understand an incident and share findings.",
    "feature.distribution.title": "Pro distribution",
    "feature.distribution.body": "App updates, stable or beta channel, pro documentation, and priority support.",
    "buy.body": "Secure payment by Stripe. Your Premium license will be prepared after confirmation.",
    "form.submit": "Continue to payment",
    "summary.note": "Payment is secure. Your Premium key will be prepared after confirmation.",
    "checkout.created": "Payment ready",
    "checkout.issued": "key confirmed after payment",
    "admin.body": "We handle purchase, licensing, and updates. The Admin Console helps IT managers prepare simple deployment across multiple computers.",
    "admin.prepare": "Preview",
    "admin.integration": "Ready for your fleet",
    "admin.item1": "Activation with the purchased organization key.",
    "admin.item2": "Guided preparation for mass deployment.",
    "admin.item3": "Tracking of computers and used licenses.",
    "admin.item4": "Optional connection to NovaSentinel Premium services.",
    "admin.droits Premium": "Configuration preview",
    "security.eyebrow": "Security",
    "security.title": "Sensitive data stays protected, and the app receives only what it needs.",
    "security.step3": "NovaSentinel securely confirms Premium rights.",
    "security.step4": "The app unlocks only authorized options.",
    "footer.login": "Sign in",
    "nav.superadmin": "Internal console",
    "superadmin.title": "Internal console to manage NovaSentinel Premium.",
    "superadmin.nav_aria": "Internal console navigation",
    "superadmin.security.roles": "Separate access for support, billing, and publishing.",
    "superadmin.security.keys": "Sensitive data is kept in a protected environment.",
  },
};

Object.assign(clientFriendlyTranslations, {
  es: {
    ...clientFriendlyTranslations.en,
    "meta.description": "NovaSentinel Premium: protección Windows complementaria, licencias profesionales y herramientas de gestión para equipos IT.",
    "nav.download": "Descargar",
    "nav.login": "Iniciar sesión",
    "hero.eyebrow": "Protección Windows complementaria",
    "hero.body": "Una aplicación clara para reforzar la protección Windows, con licencias Premium, actualizaciones de confianza y herramientas de gestión para equipos IT.",
    "trust.one.title": "Protección clara",
    "trust.one.body": "Alertas comprensibles y accionables.",
    "trust.two.title": "Privacidad",
    "trust.two.body": "Ningún archivo se envía sin una elección explícita.",
    "trust.three.title": "Acceso verificado",
    "trust.three.body": "Las opciones Premium se desbloquean de forma segura.",
    "trust.four.title": "Control local",
    "trust.four.body": "El parque informático queda bajo su control.",
    "premium.eyebrow": "Servicios Premium",
    "premium.title": "Premium añade herramientas útiles para equipos profesionales.",
    "premium.body": "NovaSentinel Premium centraliza compra, activación, actualizaciones y herramientas de gestión sin convertir la aplicación en un antivirus pesado.",
    "feature.rules.title": "Reglas de protección",
    "feature.rules.body": "Packs de protección mantenidos por NovaSentinel para mejorar la detección local.",
    "feature.cloud.title": "Reputación en línea",
    "feature.cloud.body": "Ayuda para decidir ante elementos desconocidos, con privacidad por defecto.",
    "feature.forensics.title": "Informes Pro",
    "feature.forensics.body": "Informes claros para entender un incidente y compartir conclusiones.",
    "buy.body": "Pago seguro con Stripe. Su licencia Premium se preparará tras la confirmación.",
    "form.submit": "Continuar al pago",
    "summary.note": "El pago es seguro. Su clave Premium se preparará tras la confirmación.",
    "admin.body": "Gestionamos compra, licencias y actualizaciones. Admin Console ayuda a los responsables IT a preparar despliegues sencillos en varios equipos.",
    "admin.prepare": "Ver vista previa",
    "admin.integration": "Listo para su parque",
    "admin.item1": "Activación con la clave de organización comprada.",
    "admin.item2": "Preparación guiada para despliegues en masa.",
    "admin.item3": "Seguimiento de equipos y licencias usadas.",
    "admin.item4": "Conexión opcional a los servicios Premium NovaSentinel.",
    "security.eyebrow": "Seguridad",
    "security.title": "Los datos sensibles permanecen protegidos y la aplicación solo recibe lo necesario.",
    "security.step4": "La aplicación desbloquea únicamente las opciones autorizadas.",
    "footer.login": "Iniciar sesión",
    "footer.download": "Descargar",
  },
  de: {
    ...clientFriendlyTranslations.en,
    "meta.description": "NovaSentinel Premium: ergänzender Windows-Schutz, professionelle Lizenzen und Verwaltungstools für IT-Teams.",
    "nav.download": "Herunterladen",
    "nav.login": "Anmelden",
    "hero.eyebrow": "Ergänzender Windows-Schutz",
    "hero.body": "Eine klare App für stärkeren Windows-Schutz, mit Premium-Lizenzen, vertrauenswürdigen Updates und Verwaltungstools für IT-Teams.",
    "trust.one.title": "Klarer Schutz",
    "trust.one.body": "Verständliche Hinweise, die zu konkreten Aktionen führen.",
    "trust.two.title": "Datenschutz",
    "trust.two.body": "Keine Datei wird ohne ausdrückliche Auswahl gesendet.",
    "trust.three.title": "Geprüfter Zugang",
    "trust.three.body": "Premium-Optionen werden sicher freigeschaltet.",
    "trust.four.title": "Lokale Kontrolle",
    "trust.four.body": "Ihre Computerflotte bleibt unter Ihrer Kontrolle.",
    "premium.eyebrow": "Premium-Dienste",
    "premium.title": "Premium ergänzt nützliche Werkzeuge für professionelle Teams.",
    "premium.body": "NovaSentinel Premium bündelt Kauf, Aktivierung, Updates und Verwaltungstools, ohne die App in ein schweres Antivirus zu verwandeln.",
    "feature.rules.title": "Schutzregeln",
    "feature.rules.body": "Von NovaSentinel gepflegte Schutzpakete verbessern die lokale Erkennung.",
    "feature.cloud.title": "Online-Reputation",
    "feature.cloud.body": "Entscheidungshilfe für unbekannte Elemente, mit Datenschutz als Standard.",
    "feature.forensics.title": "Pro-Berichte",
    "feature.forensics.body": "Klare Berichte, um Vorfälle zu verstehen und Erkenntnisse zu teilen.",
    "buy.body": "Sichere Zahlung mit Stripe. Ihre Premium-Lizenz wird nach Bestätigung vorbereitet.",
    "form.submit": "Weiter zur Zahlung",
    "summary.note": "Die Zahlung ist sicher. Ihr Premium-Schlüssel wird nach Bestätigung vorbereitet.",
    "admin.body": "Wir verwalten Kauf, Lizenzen und Updates. Die Admin Console hilft IT-Verantwortlichen bei einer einfachen Bereitstellung auf mehreren Computern.",
    "admin.prepare": "Vorschau anzeigen",
    "admin.integration": "Bereit für Ihre Flotte",
    "admin.item1": "Aktivierung mit dem gekauften Organisationsschlüssel.",
    "admin.item2": "Geführte Vorbereitung für Massenbereitstellung.",
    "admin.item3": "Nachverfolgung von Computern und genutzten Lizenzen.",
    "admin.item4": "Optionale Verbindung zu NovaSentinel Premium-Diensten.",
    "security.eyebrow": "Sicherheit",
    "security.title": "Sensible Daten bleiben geschützt, die App erhält nur das Notwendige.",
    "security.step4": "Die App schaltet nur autorisierte Optionen frei.",
    "footer.login": "Anmelden",
    "footer.download": "Herunterladen",
  },
  it: {
    ...clientFriendlyTranslations.en,
    "meta.description": "NovaSentinel Premium: protezione Windows complementare, licenze professionali e strumenti di gestione per team IT.",
    "nav.download": "Scarica",
    "nav.login": "Accedi",
    "hero.eyebrow": "Protezione Windows complementare",
    "hero.body": "Un'app chiara per rafforzare la protezione Windows, con licenze Premium, aggiornamenti affidabili e strumenti di gestione per team IT.",
    "trust.one.title": "Protezione chiara",
    "trust.one.body": "Avvisi comprensibili e pronti all'azione.",
    "trust.two.title": "Privacy",
    "trust.two.body": "Nessun file viene inviato senza una scelta esplicita.",
    "trust.three.title": "Accesso verificato",
    "trust.three.body": "Le opzioni Premium si sbloccano in modo sicuro.",
    "trust.four.title": "Controllo locale",
    "trust.four.body": "Il parco informatico resta sotto il tuo controllo.",
    "premium.eyebrow": "Servizi Premium",
    "premium.title": "Premium aggiunge strumenti utili ai team professionali.",
    "premium.body": "NovaSentinel Premium centralizza acquisto, attivazione, aggiornamenti e strumenti di gestione senza trasformare l'app in un antivirus pesante.",
    "feature.rules.title": "Regole di protezione",
    "feature.rules.body": "Pacchetti di protezione mantenuti da NovaSentinel per migliorare il rilevamento locale.",
    "feature.cloud.title": "Reputazione online",
    "feature.cloud.body": "Supporto decisionale per elementi sconosciuti, con privacy predefinita.",
    "feature.forensics.title": "Report Pro",
    "feature.forensics.body": "Report chiari per comprendere un incidente e condividere i risultati.",
    "buy.body": "Pagamento sicuro con Stripe. La licenza Premium sarà preparata dopo la conferma.",
    "form.submit": "Continua al pagamento",
    "summary.note": "Il pagamento è sicuro. La chiave Premium sarà preparata dopo la conferma.",
    "admin.body": "Gestiamo acquisto, licenze e aggiornamenti. Admin Console aiuta i responsabili IT a preparare un deployment semplice su più computer.",
    "admin.prepare": "Vedi anteprima",
    "admin.integration": "Pronto per il tuo parco",
    "admin.item1": "Attivazione con la chiave organizzazione acquistata.",
    "admin.item2": "Preparazione guidata per deployment di massa.",
    "admin.item3": "Monitoraggio di computer e licenze usate.",
    "admin.item4": "Connessione opzionale ai servizi Premium NovaSentinel.",
    "security.eyebrow": "Sicurezza",
    "security.title": "I dati sensibili restano protetti e l'app riceve solo il necessario.",
    "security.step4": "L'app sblocca solo le opzioni autorizzate.",
    "footer.login": "Accedi",
    "footer.download": "Scarica",
  },
  pt: {
    ...clientFriendlyTranslations.en,
    "meta.description": "NovaSentinel Premium: proteção Windows complementar, licenças profissionais e ferramentas de gestão para equipas IT.",
    "nav.download": "Transferir",
    "nav.login": "Entrar",
    "hero.eyebrow": "Proteção Windows complementar",
    "hero.body": "Uma aplicação clara para reforçar a proteção Windows, com licenças Premium, atualizações de confiança e ferramentas de gestão para equipas IT.",
    "trust.one.title": "Proteção clara",
    "trust.one.body": "Alertas compreensíveis e acionáveis.",
    "trust.two.title": "Privacidade",
    "trust.two.body": "Nenhum ficheiro é enviado sem escolha explícita.",
    "trust.three.title": "Acesso verificado",
    "trust.three.body": "As opções Premium são desbloqueadas de forma segura.",
    "trust.four.title": "Controlo local",
    "trust.four.body": "O parque informático permanece sob o seu controlo.",
    "premium.eyebrow": "Serviços Premium",
    "premium.title": "Premium adiciona ferramentas úteis para equipas profissionais.",
    "premium.body": "NovaSentinel Premium centraliza compra, ativação, atualizações e ferramentas de gestão sem transformar a aplicação num antivírus pesado.",
    "feature.rules.title": "Regras de proteção",
    "feature.rules.body": "Pacotes de proteção mantidos pela NovaSentinel para melhorar a deteção local.",
    "feature.cloud.title": "Reputação online",
    "feature.cloud.body": "Ajuda à decisão para elementos desconhecidos, com privacidade por defeito.",
    "feature.forensics.title": "Relatórios Pro",
    "feature.forensics.body": "Relatórios claros para compreender um incidente e partilhar conclusões.",
    "buy.body": "Pagamento seguro com Stripe. A licença Premium será preparada após confirmação.",
    "form.submit": "Continuar para pagamento",
    "summary.note": "O pagamento é seguro. A chave Premium será preparada após confirmação.",
    "admin.body": "Gerimos compra, licenças e atualizações. A Admin Console ajuda responsáveis IT a preparar uma instalação simples em vários computadores.",
    "admin.prepare": "Ver pré-visualização",
    "admin.integration": "Pronto para o seu parque",
    "admin.item1": "Ativação com a chave da organização comprada.",
    "admin.item2": "Preparação guiada para instalação em massa.",
    "admin.item3": "Acompanhamento de computadores e licenças usadas.",
    "admin.item4": "Ligação opcional aos serviços Premium NovaSentinel.",
    "security.eyebrow": "Segurança",
    "security.title": "Os dados sensíveis ficam protegidos e a aplicação recebe apenas o necessário.",
    "security.step4": "A aplicação desbloqueia apenas as opções autorizadas.",
    "footer.login": "Entrar",
    "footer.download": "Transferir",
  },
  ar: {
    ...clientFriendlyTranslations.en,
    "meta.description": "NovaSentinel Premium: حماية Windows إضافية وتراخيص احترافية وأدوات إدارة لفرق تقنية المعلومات.",
    "nav.download": "تنزيل",
    "nav.login": "تسجيل الدخول",
    "hero.eyebrow": "حماية Windows إضافية",
    "hero.body": "تطبيق واضح لتعزيز حماية Windows مع تراخيص Premium وتحديثات موثوقة وأدوات إدارة لفرق تقنية المعلومات.",
    "trust.one.title": "حماية واضحة",
    "trust.one.body": "تنبيهات مفهومة وقابلة للتنفيذ.",
    "trust.two.title": "الخصوصية",
    "trust.two.body": "لا يتم إرسال أي ملف دون اختيار صريح.",
    "trust.three.title": "وصول موثوق",
    "trust.three.body": "يتم فتح خيارات Premium بطريقة آمنة.",
    "trust.four.title": "تحكم محلي",
    "trust.four.body": "يبقى أسطول الأجهزة تحت سيطرتك.",
    "premium.eyebrow": "خدمات Premium",
    "premium.title": "تضيف Premium أدوات مفيدة للفرق المهنية.",
    "premium.body": "تجمع NovaSentinel Premium الشراء والتفعيل والتحديثات وأدوات الإدارة دون تحويل التطبيق إلى مضاد فيروسات ثقيل.",
    "feature.rules.title": "قواعد الحماية",
    "feature.rules.body": "حزم حماية من NovaSentinel لتحسين الكشف المحلي.",
    "feature.cloud.title": "السمعة عبر الإنترنت",
    "feature.cloud.body": "مساعدة في اتخاذ القرار للعناصر غير المعروفة مع الخصوصية كخيار افتراضي.",
    "feature.forensics.title": "تقارير Pro",
    "feature.forensics.body": "تقارير واضحة لفهم الحوادث ومشاركة النتائج.",
    "buy.body": "دفع آمن عبر Stripe. سيتم تجهيز ترخيص Premium بعد التأكيد.",
    "form.submit": "المتابعة إلى الدفع",
    "summary.note": "الدفع آمن. سيتم تجهيز مفتاح Premium بعد التأكيد.",
    "admin.body": "ندير الشراء والتراخيص والتحديثات. تساعد Admin Console مسؤولي تقنية المعلومات على تجهيز نشر بسيط على عدة أجهزة.",
    "admin.prepare": "عرض المعاينة",
    "admin.integration": "جاهز لأسطولك",
    "admin.item1": "التفعيل باستخدام مفتاح المؤسسة الذي تم شراؤه.",
    "admin.item2": "تحضير موجه للنشر على نطاق واسع.",
    "admin.item3": "متابعة الأجهزة والتراخيص المستخدمة.",
    "admin.item4": "اتصال اختياري بخدمات NovaSentinel Premium.",
    "security.eyebrow": "الأمان",
    "security.title": "تبقى البيانات الحساسة محمية ولا يستقبل التطبيق إلا ما يحتاجه.",
    "security.step4": "يفتح التطبيق الخيارات المصرح بها فقط.",
    "footer.login": "تسجيل الدخول",
    "footer.download": "تنزيل",
  },
});

Object.entries(clientFriendlyTranslations).forEach(([language, labels]) => {
  translations[language] = { ...(translations[language] || translations.fr), ...labels };
});

const form = document.querySelector("#purchaseForm");
const licenseResult = document.querySelector("#licenseResult");
const adminSnippet = document.querySelector("#adminSnippet");
const languageSelect = document.querySelector("#languageSelect");
const superadminTabs = document.querySelectorAll(".superadmin-tab");
const superadminPanels = document.querySelectorAll(".superadmin-panel");
let currentLanguage = normalizeLanguage(localStorage.getItem(languageStorageKey) || navigator.language);

function normalizeLanguage(language) {
  const code = String(language || "fr").toLowerCase().slice(0, 2);
  return Object.hasOwn(translations, code) ? code : "fr";
}

function t(key) {
  return translations[currentLanguage]?.[key] || translations.fr[key] || key;
}

function purchaseState() {
  const data = new FormData(form);
  const seats = Math.max(1, Number.parseInt(data.get("seats") || "1", 10));
  const org = String(data.get("org") || "Organisation").trim();
  const email = String(data.get("email") || "").trim();
  return { plan: "premium", seats, org, email };
}

function applyTranslations() {
  document.documentElement.lang = currentLanguage;
  document.documentElement.dir = currentLanguage === "ar" ? "rtl" : "ltr";
  document.querySelector("meta[name='description']").setAttribute("content", t("meta.description"));
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    node.textContent = t(node.dataset.i18n);
  });
  document.querySelectorAll("[data-i18n-attr]").forEach((node) => {
    node.dataset.i18nAttr.split(",").forEach((binding) => {
      const [attribute, key] = binding.split(":").map((value) => value.trim());
      if (attribute && key) {
        node.setAttribute(attribute, t(key));
      }
    });
  });
  languageSelect.value = currentLanguage;
  renderSummary();
}

function renderSummary() {
  const { seats } = purchaseState();
  document.querySelector("#summaryPlan").textContent = premiumPlan.label;
  document.querySelector("#summarySeats").textContent = String(seats);
  document.querySelector("#summaryPrice").textContent = `${seats * premiumPlan.monthly} EUR`;
  if (!licenseResult.querySelector("strong")) {
    licenseResult.innerHTML = "";
    const pending = document.createElement("span");
    pending.textContent = t("summary.pending");
    licenseResult.append(pending);
  }
  renderAdminSnippet();
}

function renderAdminSnippet(key = "PREMIUM_KEY_AFTER_PAYMENT") {
  const { seats, org } = purchaseState();
  const payload = {
    organization: org,
    plan: "premium",
    seat_limit: seats,
    license_key: key,
    admin_console: "downloadable",
    hosted_by_novasentinel: ["purchase", "license_management", "premium_rights", "updates", "hash_reputation"],
    payment_provider: "stripe",
    customer_local: ["deployment_scripts", "bulk_license_csv", "preconfiguration_json"],
  };
  adminSnippet.textContent = [
    "%ProgramData%\\NovaSentinel\\premium_deployment.json",
    JSON.stringify({ license_key: key }, null, 2),
    "",
    t("admin.droits Premium"),
    JSON.stringify({ ...payload, features: premiumFeatures }, null, 2),
  ].join("\n");
}

function renderLicenseResult(key, email, seats) {
  licenseResult.innerHTML = "";
  const wrapper = document.createElement("div");
  const label = document.createElement("span");
  const strong = document.createElement("strong");
  const detail = document.createElement("small");
  label.textContent = t("checkout.created");
  strong.textContent = key;
  detail.textContent = `${premiumPlan.label} | ${seats} ${t("summary.seats").toLowerCase()} | ${email} | ${t("checkout.issued")}`;
  wrapper.append(label, strong, detail);
  licenseResult.append(wrapper);
}

async function postJson(path, payload) {
  const response = await fetch(path, {
    method: "POST",
    credentials: "same-origin",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(data.message || data.error || `HTTP ${response.status}`);
  }
  return data;
}

function renderCheckoutError(message) {
  licenseResult.innerHTML = "";
  const wrapper = document.createElement("div");
  const label = document.createElement("span");
  const detail = document.createElement("small");
  label.textContent = "Stripe";
  detail.textContent = message;
  wrapper.append(label, detail);
  licenseResult.append(wrapper);
}

languageSelect.addEventListener("change", () => {
  currentLanguage = normalizeLanguage(languageSelect.value);
  localStorage.setItem(languageStorageKey, currentLanguage);
  applyTranslations();
});

form.addEventListener("input", renderSummary);
form.addEventListener("change", renderSummary);
form.addEventListener("submit", async (event) => {
  event.preventDefault();
  const { org, email, seats } = purchaseState();
  try {
    const checkout = await postJson("/api/checkout/sessions", { org, email, seats });
    renderLicenseResult(checkout.id, email, seats);
    window.location.href = checkout.stripe_checkout_url;
  } catch (error) {
    renderCheckoutError(error.message);
    renderAdminSnippet();
  }
});

document.querySelector("#adminPreview").addEventListener("click", () => {
  document.querySelector("#admin-console").scrollIntoView({ behavior: "smooth", block: "start" });
  renderAdminSnippet(licenseResult.querySelector("strong")?.textContent || "PREMIUM_KEY_AFTER_PAYMENT");
});

superadminTabs.forEach((tab) => {
  tab.addEventListener("click", () => {
    const target = tab.dataset.panel;
    superadminTabs.forEach((item) => item.classList.toggle("active", item === tab));
    superadminPanels.forEach((panel) => panel.classList.toggle("active", panel.dataset.panel === target));
  });
});

applyTranslations();
