const premiumPlan = { label: "Premium", monthly: 12, prefix: "NSP-PREMIUM" };
const languageStorageKey = "novasentinel_premium_language";

const premiumFeatures = [
  "premium_updates",
  "detection_rule_updates",
  "cloud_reputation",
  "privacy_mode",
  "advanced_ransomware",
  "advanced_behavior",
  "forensics_pro",
  "advanced_scheduling",
  "fleet_console",
  "admin_console_download",
  "mass_deployment",
  "bulk_license_management",
  "preconfiguration_packages",
  "enterprise_mode",
  "silent_install",
  "deployment_grouping",
  "license_csv_export",
  "deployment_audit",
];

const translations = {
  fr: {
    "meta.description": "NovaSentinel Premium: défense Windows complémentaire, licences professionnelles, réputation hash, règles signées et Admin Console téléchargeable.",
    "nav.aria": "Navigation principale",
    "nav.download": "Download",
    "nav.premium": "Premium",
    "nav.buy": "Acheter",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Sécurité",
    "language.label": "Langue",
    "language.aria": "Langue du site",
    "hero.eyebrow": "Défense Windows complémentaire",
    "hero.body": "Une application de protection explicable pour Windows, avec services Premium hébergés par NovaSentinel: licences, mises à jour signées, réputation hash et distribution professionnelle.",
    "download.aria": "Téléchargement NovaSentinel",
    "download.title": "Télécharger NovaSentinel",
    "download.body": "Version Windows avec activation Premium optionnelle",
    "download.button": "Download",
    "trust.aria": "Modèle de confiance",
    "trust.one.title": "Pas un EDR",
    "trust.one.body": "Pas de promesse kernel ou mini-filter.",
    "trust.two.title": "Hash first",
    "trust.two.body": "Pas d'upload de fichiers par défaut.",
    "trust.three.title": "Clé signée",
    "trust.three.body": "Droits Premium vérifiés localement.",
    "trust.four.title": "Admin local",
    "trust.four.body": "Le parc client reste chez le client.",
    "premium.eyebrow": "Ce que nous hébergeons",
    "premium.title": "Premium ajoute des services professionnels, pas un faux moteur antivirus.",
    "premium.body": "NovaSentinel reste une défense complémentaire. Le cloud NovaSentinel sert aux licences, règles signées, réputation par hash, mises à jour, achat et distribution.",
    "feature.rules.title": "Règles et IOC signés",
    "feature.rules.body": "Base de hashs/signatures, seuils heuristiques enrichis et listes d'IOC distribués en packs signés.",
    "feature.cloud.title": "Réputation cloud",
    "feature.cloud.body": "Vérification des hashs inconnus, score serveur privé, cache local et mode confidentialité.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "Rapports PDF/HTML, timeline d'incident, exports JSON/CSV et preuves enrichies.",
    "feature.distribution.title": "Distribution pro",
    "feature.distribution.body": "Auto-update de l'application, canal stable/beta, documentation pro et support prioritaire.",
    "buy.eyebrow": "Achat de clé",
    "buy.title": "Choisissez le nombre de postes et générez une clé Premium.",
    "buy.body": "Paiement prévu via Stripe Checkout. En production, le backend créera la licence seulement après webhook Stripe confirmé, puis signera les entitlements.",
    "form.org": "Organisation",
    "form.email": "Email responsable",
    "form.plan": "Plan",
    "form.plan_body": "Toutes les options Premium, facturées selon le nombre de postes.",
    "form.seats": "Nombre de postes",
    "form.submit": "Continuer avec Stripe",
    "summary.title": "Résumé",
    "summary.plan": "Plan",
    "summary.seats": "Postes",
    "summary.price": "Total mensuel",
    "summary.pending": "Clé générée après validation achat",
    "summary.note": "Stripe Checkout gérera le paiement. La clé organisation est créée côté serveur après confirmation.",
    "checkout.created": "Session Stripe créée",
    "checkout.issued": "clé émise après webhook",
    "admin.eyebrow": "Pour responsables de parc",
    "admin.title": "NovaSentinel Admin Console sera téléchargeable.",
    "admin.body": "Nous hébergeons l'achat, les licences, les signatures et les mises à jour. L'Admin Console se télécharge côté client pour préparer les déploiements de masse, les clés Premium et les paquets de préconfiguration.",
    "admin.download": "Télécharger NovaSentinel",
    "admin.prepare": "Préparer Admin Console",
    "admin.integration": "Intégration prévue",
    "admin.item1": "Import de la clé organisation achetée.",
    "admin.item2": "Génération de scripts GPO, Intune, RMM et PowerShell.",
    "admin.item3": "Paquets JSON de préconfiguration et modèle CSV licences.",
    "admin.item4": "Synchronisation optionnelle avec l'API licence NovaSentinel.",
    "admin.entitlement": "Aperçu entitlement",
    "security.eyebrow": "Architecture sécurisée",
    "security.title": "Le secret reste côté NovaSentinel. L'app ne vérifie que des preuves signées.",
    "security.step1": "Achat et création de licence sur notre site.",
    "security.step2": "Activation par clé client ou clé organisation.",
    "security.step3": "Serveur NovaSentinel retourne un entitlement Ed25519 signé.",
    "security.step4": "L'app déverrouille seulement les droits signés et non expirés.",
    "footer.buy": "Acheter une clé",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Download",
  },
  en: {
    "meta.description": "NovaSentinel Premium: complementary Windows defense, professional licensing, hash reputation, signed rules, and downloadable Admin Console.",
    "nav.aria": "Main navigation",
    "nav.download": "Download",
    "nav.premium": "Premium",
    "nav.buy": "Buy",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Security",
    "language.label": "Language",
    "language.aria": "Site language",
    "hero.eyebrow": "Complementary Windows defense",
    "hero.body": "An explainable Windows protection app with NovaSentinel-hosted Premium services: licensing, signed updates, hash reputation, and professional distribution.",
    "download.aria": "NovaSentinel download",
    "download.title": "Download NovaSentinel",
    "download.body": "Windows version with optional Premium activation",
    "download.button": "Download",
    "trust.aria": "Trust model",
    "trust.one.title": "Not an EDR",
    "trust.one.body": "No kernel or mini-filter promise.",
    "trust.two.title": "Hash first",
    "trust.two.body": "No file upload by default.",
    "trust.three.title": "Signed key",
    "trust.three.body": "Premium rights verified locally.",
    "trust.four.title": "Local admin",
    "trust.four.body": "The customer fleet stays with the customer.",
    "premium.eyebrow": "What we host",
    "premium.title": "Premium adds professional services, not a fake antivirus engine.",
    "premium.body": "NovaSentinel remains a complementary defense. NovaSentinel Cloud handles licensing, signed rules, hash reputation, updates, purchase, and distribution.",
    "feature.rules.title": "Signed rules and IOCs",
    "feature.rules.body": "Hash/signature base, enriched heuristic thresholds, and IOC lists distributed as signed packs.",
    "feature.cloud.title": "Cloud reputation",
    "feature.cloud.body": "Unknown hash checks, private server score, local cache, and privacy mode.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "PDF/HTML reports, incident timeline, JSON/CSV exports, and enriched evidence.",
    "feature.distribution.title": "Pro distribution",
    "feature.distribution.body": "App auto-update, stable/beta channel, pro documentation, and priority support.",
    "buy.eyebrow": "Key purchase",
    "buy.title": "Choose the seat count and generate a Premium key.",
    "buy.body": "Payment is planned through Stripe Checkout. In production, the backend creates the license only after a confirmed Stripe webhook, then signs the entitlements.",
    "form.org": "Organization",
    "form.email": "IT contact email",
    "form.plan": "Plan",
    "form.plan_body": "All Premium options, billed by seat count.",
    "form.seats": "Seat count",
    "form.submit": "Continue with Stripe",
    "summary.title": "Summary",
    "summary.plan": "Plan",
    "summary.seats": "Seats",
    "summary.price": "Monthly total",
    "summary.pending": "Key generated after purchase validation",
    "summary.note": "Stripe Checkout will handle payment. The organization key is created server-side after confirmation.",
    "checkout.created": "Stripe session created",
    "checkout.issued": "key issued after webhook",
    "admin.eyebrow": "For fleet managers",
    "admin.title": "NovaSentinel Admin Console will be downloadable.",
    "admin.body": "We host purchase, licensing, signatures, and updates. The Admin Console is downloaded on the customer side to prepare mass deployments, Premium keys, and preconfiguration packages.",
    "admin.download": "Download NovaSentinel",
    "admin.prepare": "Prepare Admin Console",
    "admin.integration": "Planned integration",
    "admin.item1": "Import the purchased organization key.",
    "admin.item2": "Generate GPO, Intune, RMM, and PowerShell scripts.",
    "admin.item3": "JSON preconfiguration packages and license CSV template.",
    "admin.item4": "Optional sync with the NovaSentinel license API.",
    "admin.entitlement": "Entitlement preview",
    "security.eyebrow": "Secure architecture",
    "security.title": "The secret stays on NovaSentinel's side. The app only verifies signed proofs.",
    "security.step1": "Purchase and license creation on our site.",
    "security.step2": "Activation by customer key or organization key.",
    "security.step3": "NovaSentinel server returns a signed Ed25519 entitlement.",
    "security.step4": "The app unlocks only signed, non-expired rights.",
    "footer.buy": "Buy a key",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Download",
  },
  es: {
    "meta.description": "NovaSentinel Premium: defensa complementaria para Windows, licencias profesionales, reputación de hash, reglas firmadas y Admin Console descargable.",
    "nav.aria": "Navegación principal",
    "nav.download": "Descargar",
    "nav.premium": "Premium",
    "nav.buy": "Comprar",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Seguridad",
    "language.label": "Idioma",
    "language.aria": "Idioma del sitio",
    "hero.eyebrow": "Defensa complementaria para Windows",
    "hero.body": "Una aplicación de protección explicable para Windows con servicios Premium alojados por NovaSentinel: licencias, actualizaciones firmadas, reputación de hash y distribución profesional.",
    "download.aria": "Descarga de NovaSentinel",
    "download.title": "Descargar NovaSentinel",
    "download.body": "Versión Windows con activación Premium opcional",
    "download.button": "Descargar",
    "trust.aria": "Modelo de confianza",
    "trust.one.title": "No es un EDR",
    "trust.one.body": "Sin promesa de kernel ni mini-filter.",
    "trust.two.title": "Hash primero",
    "trust.two.body": "Sin subida de archivos por defecto.",
    "trust.three.title": "Clave firmada",
    "trust.three.body": "Derechos Premium verificados localmente.",
    "trust.four.title": "Admin local",
    "trust.four.body": "El parque del cliente permanece con el cliente.",
    "premium.eyebrow": "Lo que alojamos",
    "premium.title": "Premium añade servicios profesionales, no un motor antivirus falso.",
    "premium.body": "NovaSentinel sigue siendo una defensa complementaria. NovaSentinel Cloud gestiona licencias, reglas firmadas, reputación por hash, actualizaciones, compra y distribución.",
    "feature.rules.title": "Reglas e IOC firmados",
    "feature.rules.body": "Base de hashes/firmas, umbrales heurísticos enriquecidos y listas IOC distribuidas en paquetes firmados.",
    "feature.cloud.title": "Reputación cloud",
    "feature.cloud.body": "Verificación de hashes desconocidos, puntuación privada del servidor, caché local y modo privacidad.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "Informes PDF/HTML, timeline de incidente, exportaciones JSON/CSV y evidencias enriquecidas.",
    "feature.distribution.title": "Distribución pro",
    "feature.distribution.body": "Auto-update de la aplicación, canal stable/beta, documentación pro y soporte prioritario.",
    "buy.eyebrow": "Compra de clave",
    "buy.title": "Elige el número de puestos y genera una clave Premium.",
    "buy.body": "El pago está previsto mediante Stripe Checkout. En producción, el backend crea la licencia solo después del webhook Stripe confirmado y firma los entitlements.",
    "form.org": "Organización",
    "form.email": "Email responsable",
    "form.plan": "Plan",
    "form.plan_body": "Todas las opciones Premium, facturadas según el número de puestos.",
    "form.seats": "Número de puestos",
    "form.submit": "Continuar con Stripe",
    "summary.title": "Resumen",
    "summary.plan": "Plan",
    "summary.seats": "Puestos",
    "summary.price": "Total mensual",
    "summary.pending": "Clave generada tras validar la compra",
    "summary.note": "Stripe Checkout gestionará el pago. La clave de organización se crea en el servidor tras la confirmación.",
    "checkout.created": "Sesión Stripe creada",
    "checkout.issued": "clave emitida tras webhook",
    "admin.eyebrow": "Para responsables de parque",
    "admin.title": "NovaSentinel Admin Console será descargable.",
    "admin.body": "Alojamos la compra, licencias, firmas y actualizaciones. La Admin Console se descarga en el cliente para preparar despliegues masivos, claves Premium y paquetes de preconfiguración.",
    "admin.download": "Descargar NovaSentinel",
    "admin.prepare": "Preparar Admin Console",
    "admin.integration": "Integración prevista",
    "admin.item1": "Importar la clave de organización comprada.",
    "admin.item2": "Generar scripts GPO, Intune, RMM y PowerShell.",
    "admin.item3": "Paquetes JSON de preconfiguración y plantilla CSV de licencias.",
    "admin.item4": "Sincronización opcional con la API de licencias NovaSentinel.",
    "admin.entitlement": "Vista previa del entitlement",
    "security.eyebrow": "Arquitectura segura",
    "security.title": "El secreto queda del lado de NovaSentinel. La app solo verifica pruebas firmadas.",
    "security.step1": "Compra y creación de licencia en nuestro sitio.",
    "security.step2": "Activación por clave de cliente o clave de organización.",
    "security.step3": "El servidor NovaSentinel devuelve un entitlement Ed25519 firmado.",
    "security.step4": "La app desbloquea solo derechos firmados y no expirados.",
    "footer.buy": "Comprar una clave",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Descargar",
  },
  de: {
    "meta.description": "NovaSentinel Premium: ergänzende Windows-Verteidigung, professionelle Lizenzen, Hash-Reputation, signierte Regeln und herunterladbare Admin Console.",
    "nav.aria": "Hauptnavigation",
    "nav.download": "Download",
    "nav.premium": "Premium",
    "nav.buy": "Kaufen",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Sicherheit",
    "language.label": "Sprache",
    "language.aria": "Sprache der Website",
    "hero.eyebrow": "Ergänzende Windows-Verteidigung",
    "hero.body": "Eine erklärbare Windows-Schutz-App mit von NovaSentinel gehosteten Premium-Diensten: Lizenzen, signierte Updates, Hash-Reputation und professionelle Verteilung.",
    "download.aria": "NovaSentinel Download",
    "download.title": "NovaSentinel herunterladen",
    "download.body": "Windows-Version mit optionaler Premium-Aktivierung",
    "download.button": "Download",
    "trust.aria": "Vertrauensmodell",
    "trust.one.title": "Kein EDR",
    "trust.one.body": "Keine Kernel- oder Mini-Filter-Zusage.",
    "trust.two.title": "Hash first",
    "trust.two.body": "Standardmäßig kein Datei-Upload.",
    "trust.three.title": "Signierter Schlüssel",
    "trust.three.body": "Premium-Rechte werden lokal geprüft.",
    "trust.four.title": "Lokale Admins",
    "trust.four.body": "Die Kundenflotte bleibt beim Kunden.",
    "premium.eyebrow": "Was wir hosten",
    "premium.title": "Premium ergänzt professionelle Dienste, keinen falschen Antivirus-Motor.",
    "premium.body": "NovaSentinel bleibt eine ergänzende Verteidigung. NovaSentinel Cloud verwaltet Lizenzen, signierte Regeln, Hash-Reputation, Updates, Kauf und Verteilung.",
    "feature.rules.title": "Signierte Regeln und IOCs",
    "feature.rules.body": "Hash-/Signaturbasis, erweiterte Heuristik-Schwellen und IOC-Listen als signierte Pakete.",
    "feature.cloud.title": "Cloud-Reputation",
    "feature.cloud.body": "Prüfung unbekannter Hashes, privater Server-Score, lokaler Cache und Datenschutzmodus.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "PDF/HTML-Berichte, Incident-Timeline, JSON/CSV-Exporte und angereicherte Nachweise.",
    "feature.distribution.title": "Pro-Verteilung",
    "feature.distribution.body": "App-Auto-Update, stable/beta Kanal, Pro-Dokumentation und priorisierter Support.",
    "buy.eyebrow": "Schlüsselkauf",
    "buy.title": "Wählen Sie die Anzahl der Plätze und generieren Sie einen Premium-Schlüssel.",
    "buy.body": "Die Zahlung ist über Stripe Checkout vorgesehen. In Produktion erstellt das Backend die Lizenz erst nach bestätigtem Stripe-Webhook und signiert dann die Entitlements.",
    "form.org": "Organisation",
    "form.email": "IT-Kontakt-E-Mail",
    "form.plan": "Plan",
    "form.plan_body": "Alle Premium-Optionen, nach Anzahl der Plätze abgerechnet.",
    "form.seats": "Anzahl Plätze",
    "form.submit": "Weiter mit Stripe",
    "summary.title": "Zusammenfassung",
    "summary.plan": "Plan",
    "summary.seats": "Plätze",
    "summary.price": "Monatssumme",
    "summary.pending": "Schlüssel nach Kaufvalidierung generiert",
    "summary.note": "Stripe Checkout verarbeitet die Zahlung. Der Organisationsschlüssel wird nach Bestätigung serverseitig erstellt.",
    "checkout.created": "Stripe-Sitzung erstellt",
    "checkout.issued": "Schlüssel nach Webhook ausgestellt",
    "admin.eyebrow": "Für Flottenverantwortliche",
    "admin.title": "NovaSentinel Admin Console wird herunterladbar sein.",
    "admin.body": "Wir hosten Kauf, Lizenzen, Signaturen und Updates. Die Admin Console wird beim Kunden heruntergeladen, um Massenbereitstellungen, Premium-Schlüssel und Vorkonfigurationspakete vorzubereiten.",
    "admin.download": "NovaSentinel herunterladen",
    "admin.prepare": "Admin Console vorbereiten",
    "admin.integration": "Geplante Integration",
    "admin.item1": "Gekauften Organisationsschlüssel importieren.",
    "admin.item2": "GPO-, Intune-, RMM- und PowerShell-Skripte generieren.",
    "admin.item3": "JSON-Vorkonfigurationspakete und Lizenz-CSV-Vorlage.",
    "admin.item4": "Optionale Synchronisierung mit der NovaSentinel-Lizenz-API.",
    "admin.entitlement": "Entitlement-Vorschau",
    "security.eyebrow": "Sichere Architektur",
    "security.title": "Das Geheimnis bleibt bei NovaSentinel. Die App prüft nur signierte Nachweise.",
    "security.step1": "Kauf und Lizenzerstellung auf unserer Website.",
    "security.step2": "Aktivierung per Kundenschlüssel oder Organisationsschlüssel.",
    "security.step3": "Der NovaSentinel-Server liefert ein signiertes Ed25519-Entitlement.",
    "security.step4": "Die App entsperrt nur signierte, nicht abgelaufene Rechte.",
    "footer.buy": "Schlüssel kaufen",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Download",
  },
  it: {
    "meta.description": "NovaSentinel Premium: difesa Windows complementare, licenze professionali, reputazione hash, regole firmate e Admin Console scaricabile.",
    "nav.aria": "Navigazione principale",
    "nav.download": "Download",
    "nav.premium": "Premium",
    "nav.buy": "Acquista",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Sicurezza",
    "language.label": "Lingua",
    "language.aria": "Lingua del sito",
    "hero.eyebrow": "Difesa Windows complementare",
    "hero.body": "Un'app di protezione spiegabile per Windows con servizi Premium ospitati da NovaSentinel: licenze, aggiornamenti firmati, reputazione hash e distribuzione professionale.",
    "download.aria": "Download NovaSentinel",
    "download.title": "Scarica NovaSentinel",
    "download.body": "Versione Windows con attivazione Premium opzionale",
    "download.button": "Download",
    "trust.aria": "Modello di fiducia",
    "trust.one.title": "Non è un EDR",
    "trust.one.body": "Nessuna promessa kernel o mini-filter.",
    "trust.two.title": "Hash first",
    "trust.two.body": "Nessun upload di file per impostazione predefinita.",
    "trust.three.title": "Chiave firmata",
    "trust.three.body": "Diritti Premium verificati localmente.",
    "trust.four.title": "Admin locale",
    "trust.four.body": "Il parco del cliente resta presso il cliente.",
    "premium.eyebrow": "Cosa ospitiamo",
    "premium.title": "Premium aggiunge servizi professionali, non un falso motore antivirus.",
    "premium.body": "NovaSentinel resta una difesa complementare. NovaSentinel Cloud gestisce licenze, regole firmate, reputazione hash, aggiornamenti, acquisto e distribuzione.",
    "feature.rules.title": "Regole e IOC firmati",
    "feature.rules.body": "Base hash/firme, soglie euristiche arricchite e liste IOC distribuite in pacchetti firmati.",
    "feature.cloud.title": "Reputazione cloud",
    "feature.cloud.body": "Verifica degli hash sconosciuti, punteggio server privato, cache locale e modalità privacy.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "Report PDF/HTML, timeline incidente, export JSON/CSV e prove arricchite.",
    "feature.distribution.title": "Distribuzione pro",
    "feature.distribution.body": "Auto-update dell'app, canale stable/beta, documentazione pro e supporto prioritario.",
    "buy.eyebrow": "Acquisto chiave",
    "buy.title": "Scegli il numero di postazioni e genera una chiave Premium.",
    "buy.body": "Il pagamento è previsto tramite Stripe Checkout. In produzione il backend crea la licenza solo dopo il webhook Stripe confermato, poi firma gli entitlement.",
    "form.org": "Organizzazione",
    "form.email": "Email responsabile",
    "form.plan": "Piano",
    "form.plan_body": "Tutte le opzioni Premium, fatturate in base al numero di postazioni.",
    "form.seats": "Numero postazioni",
    "form.submit": "Continua con Stripe",
    "summary.title": "Riepilogo",
    "summary.plan": "Piano",
    "summary.seats": "Postazioni",
    "summary.price": "Totale mensile",
    "summary.pending": "Chiave generata dopo la validazione dell'acquisto",
    "summary.note": "Stripe Checkout gestirà il pagamento. La chiave organizzazione viene creata lato server dopo la conferma.",
    "checkout.created": "Sessione Stripe creata",
    "checkout.issued": "chiave emessa dopo webhook",
    "admin.eyebrow": "Per responsabili di parco",
    "admin.title": "NovaSentinel Admin Console sarà scaricabile.",
    "admin.body": "Ospitiamo acquisto, licenze, firme e aggiornamenti. L'Admin Console viene scaricata dal cliente per preparare distribuzioni massive, chiavi Premium e pacchetti di preconfigurazione.",
    "admin.download": "Scarica NovaSentinel",
    "admin.prepare": "Prepara Admin Console",
    "admin.integration": "Integrazione prevista",
    "admin.item1": "Import della chiave organizzazione acquistata.",
    "admin.item2": "Generazione di script GPO, Intune, RMM e PowerShell.",
    "admin.item3": "Pacchetti JSON di preconfigurazione e modello CSV licenze.",
    "admin.item4": "Sincronizzazione opzionale con l'API licenze NovaSentinel.",
    "admin.entitlement": "Anteprima entitlement",
    "security.eyebrow": "Architettura sicura",
    "security.title": "Il segreto resta lato NovaSentinel. L'app verifica solo prove firmate.",
    "security.step1": "Acquisto e creazione licenza sul nostro sito.",
    "security.step2": "Attivazione con chiave cliente o chiave organizzazione.",
    "security.step3": "Il server NovaSentinel restituisce un entitlement Ed25519 firmato.",
    "security.step4": "L'app sblocca solo diritti firmati e non scaduti.",
    "footer.buy": "Acquista una chiave",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Download",
  },
  pt: {
    "meta.description": "NovaSentinel Premium: defesa Windows complementar, licenças profissionais, reputação hash, regras assinadas e Admin Console transferível.",
    "nav.aria": "Navegação principal",
    "nav.download": "Download",
    "nav.premium": "Premium",
    "nav.buy": "Comprar",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "Segurança",
    "language.label": "Idioma",
    "language.aria": "Idioma do site",
    "hero.eyebrow": "Defesa Windows complementar",
    "hero.body": "Uma aplicação de proteção explicável para Windows com serviços Premium alojados pela NovaSentinel: licenças, atualizações assinadas, reputação hash e distribuição profissional.",
    "download.aria": "Download NovaSentinel",
    "download.title": "Transferir NovaSentinel",
    "download.body": "Versão Windows com ativação Premium opcional",
    "download.button": "Download",
    "trust.aria": "Modelo de confiança",
    "trust.one.title": "Não é um EDR",
    "trust.one.body": "Sem promessa kernel ou mini-filter.",
    "trust.two.title": "Hash first",
    "trust.two.body": "Sem upload de ficheiros por defeito.",
    "trust.three.title": "Chave assinada",
    "trust.three.body": "Direitos Premium verificados localmente.",
    "trust.four.title": "Admin local",
    "trust.four.body": "O parque do cliente fica no cliente.",
    "premium.eyebrow": "O que alojamos",
    "premium.title": "Premium adiciona serviços profissionais, não um falso motor antivírus.",
    "premium.body": "NovaSentinel continua a ser uma defesa complementar. O NovaSentinel Cloud gere licenças, regras assinadas, reputação por hash, atualizações, compra e distribuição.",
    "feature.rules.title": "Regras e IOC assinados",
    "feature.rules.body": "Base de hashes/assinaturas, limites heurísticos enriquecidos e listas IOC distribuídas em pacotes assinados.",
    "feature.cloud.title": "Reputação cloud",
    "feature.cloud.body": "Verificação de hashes desconhecidos, pontuação de servidor privado, cache local e modo privacidade.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "Relatórios PDF/HTML, timeline de incidente, exportações JSON/CSV e provas enriquecidas.",
    "feature.distribution.title": "Distribuição pro",
    "feature.distribution.body": "Auto-update da aplicação, canal stable/beta, documentação pro e suporte prioritário.",
    "buy.eyebrow": "Compra de chave",
    "buy.title": "Escolha o número de postos e gere uma chave Premium.",
    "buy.body": "O pagamento está previsto via Stripe Checkout. Em produção, o backend cria a licença só após webhook Stripe confirmado e depois assina os entitlements.",
    "form.org": "Organização",
    "form.email": "Email responsável",
    "form.plan": "Plano",
    "form.plan_body": "Todas as opções Premium, faturadas pelo número de postos.",
    "form.seats": "Número de postos",
    "form.submit": "Continuar com Stripe",
    "summary.title": "Resumo",
    "summary.plan": "Plano",
    "summary.seats": "Postos",
    "summary.price": "Total mensal",
    "summary.pending": "Chave gerada após validação da compra",
    "summary.note": "Stripe Checkout vai gerir o pagamento. A chave da organização é criada no servidor após confirmação.",
    "checkout.created": "Sessão Stripe criada",
    "checkout.issued": "chave emitida após webhook",
    "admin.eyebrow": "Para responsáveis de parque",
    "admin.title": "NovaSentinel Admin Console será transferível.",
    "admin.body": "Alojamos compra, licenças, assinaturas e atualizações. A Admin Console é transferida no cliente para preparar implantações em massa, chaves Premium e pacotes de pré-configuração.",
    "admin.download": "Transferir NovaSentinel",
    "admin.prepare": "Preparar Admin Console",
    "admin.integration": "Integração prevista",
    "admin.item1": "Importar a chave de organização comprada.",
    "admin.item2": "Gerar scripts GPO, Intune, RMM e PowerShell.",
    "admin.item3": "Pacotes JSON de pré-configuração e modelo CSV de licenças.",
    "admin.item4": "Sincronização opcional com a API de licenças NovaSentinel.",
    "admin.entitlement": "Pré-visualização entitlement",
    "security.eyebrow": "Arquitetura segura",
    "security.title": "O segredo fica do lado da NovaSentinel. A app só verifica provas assinadas.",
    "security.step1": "Compra e criação de licença no nosso site.",
    "security.step2": "Ativação por chave cliente ou chave organização.",
    "security.step3": "O servidor NovaSentinel devolve um entitlement Ed25519 assinado.",
    "security.step4": "A app desbloqueia apenas direitos assinados e não expirados.",
    "footer.buy": "Comprar uma chave",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "Download",
  },
  ar: {
    "meta.description": "NovaSentinel Premium: دفاع Windows تكميلي، تراخيص احترافية، سمعة hash، قواعد موقعة و Admin Console قابلة للتنزيل.",
    "nav.aria": "التنقل الرئيسي",
    "nav.download": "تنزيل",
    "nav.premium": "Premium",
    "nav.buy": "شراء",
    "nav.admin": "Admin Console",
    "nav.login": "Login",
    "nav.security": "الأمان",
    "language.label": "اللغة",
    "language.aria": "لغة الموقع",
    "hero.eyebrow": "دفاع Windows تكميلي",
    "hero.body": "تطبيق حماية قابل للشرح لـ Windows مع خدمات Premium مستضافة من NovaSentinel: التراخيص، التحديثات الموقعة، سمعة hash والتوزيع الاحترافي.",
    "download.aria": "تنزيل NovaSentinel",
    "download.title": "تنزيل NovaSentinel",
    "download.body": "إصدار Windows مع تفعيل Premium اختياري",
    "download.button": "تنزيل",
    "trust.aria": "نموذج الثقة",
    "trust.one.title": "ليس EDR",
    "trust.one.body": "لا وعود kernel أو mini-filter.",
    "trust.two.title": "Hash أولا",
    "trust.two.body": "لا رفع ملفات افتراضيا.",
    "trust.three.title": "مفتاح موقع",
    "trust.three.body": "حقوق Premium تتحقق محليا.",
    "trust.four.title": "إدارة محلية",
    "trust.four.body": "أجهزة العميل تبقى لدى العميل.",
    "premium.eyebrow": "ما نستضيفه",
    "premium.title": "Premium يضيف خدمات احترافية، وليس محرك مضاد فيروسات وهميا.",
    "premium.body": "يبقى NovaSentinel دفاعا تكميليا. NovaSentinel Cloud يدير التراخيص، القواعد الموقعة، سمعة hash، التحديثات، الشراء والتوزيع.",
    "feature.rules.title": "قواعد و IOC موقعة",
    "feature.rules.body": "قاعدة hashes/signatures وحدود heuristics محسنة وقوائم IOC موزعة كحزم موقعة.",
    "feature.cloud.title": "سمعة cloud",
    "feature.cloud.body": "فحص hashes غير المعروفة، نتيجة خادم خاص، cache محلي ووضع خصوصية.",
    "feature.forensics.title": "Forensics Pro",
    "feature.forensics.body": "تقارير PDF/HTML، timeline للحادث، تصدير JSON/CSV وأدلة محسنة.",
    "feature.distribution.title": "توزيع احترافي",
    "feature.distribution.body": "تحديث تلقائي للتطبيق، قناة stable/beta، توثيق احترافي ودعم أولوية.",
    "buy.eyebrow": "شراء مفتاح",
    "buy.title": "اختر عدد الأجهزة وأنشئ مفتاح Premium.",
    "buy.body": "الدفع مخطط عبر Stripe Checkout. في الإنتاج ينشئ backend الترخيص فقط بعد webhook مؤكد من Stripe ثم يوقع entitlements.",
    "form.org": "المؤسسة",
    "form.email": "بريد مسؤول IT",
    "form.plan": "الخطة",
    "form.plan_body": "كل خيارات Premium، مع فوترة حسب عدد الأجهزة.",
    "form.seats": "عدد الأجهزة",
    "form.submit": "المتابعة مع Stripe",
    "summary.title": "الملخص",
    "summary.plan": "الخطة",
    "summary.seats": "الأجهزة",
    "summary.price": "الإجمالي الشهري",
    "summary.pending": "يتم إنشاء المفتاح بعد تأكيد الشراء",
    "summary.note": "سيتولى Stripe Checkout الدفع. يتم إنشاء مفتاح المؤسسة على الخادم بعد التأكيد.",
    "checkout.created": "تم إنشاء جلسة Stripe",
    "checkout.issued": "مفتاح يصدر بعد webhook",
    "admin.eyebrow": "لمسؤولي الأجهزة",
    "admin.title": "NovaSentinel Admin Console ستكون قابلة للتنزيل.",
    "admin.body": "نحن نستضيف الشراء والتراخيص والتوقيعات والتحديثات. يتم تنزيل Admin Console لدى العميل لتحضير النشر الجماعي ومفاتيح Premium وحزم التهيئة المسبقة.",
    "admin.download": "تنزيل NovaSentinel",
    "admin.prepare": "تحضير Admin Console",
    "admin.integration": "التكامل المخطط",
    "admin.item1": "استيراد مفتاح المؤسسة المشترى.",
    "admin.item2": "إنشاء scripts لـ GPO و Intune و RMM و PowerShell.",
    "admin.item3": "حزم JSON للتهيئة المسبقة وقالب CSV للتراخيص.",
    "admin.item4": "مزامنة اختيارية مع NovaSentinel license API.",
    "admin.entitlement": "معاينة entitlement",
    "security.eyebrow": "هندسة آمنة",
    "security.title": "يبقى السر لدى NovaSentinel. التطبيق يتحقق فقط من أدلة موقعة.",
    "security.step1": "الشراء وإنشاء الترخيص على موقعنا.",
    "security.step2": "التفعيل بمفتاح عميل أو مفتاح مؤسسة.",
    "security.step3": "يعيد خادم NovaSentinel entitlement موقعا بـ Ed25519.",
    "security.step4": "يفتح التطبيق فقط الحقوق الموقعة وغير المنتهية.",
    "footer.buy": "شراء مفتاح",
    "footer.admin": "Admin Console",
    "footer.login": "Login",
    "footer.download": "تنزيل",
  },
};

const superadminTranslations = {
  fr: {
    "nav.superadmin": "Superadmin",
    "superadmin.eyebrow": "Interne NovaSentinel",
    "superadmin.title": "Dashboard Superadmin pour piloter Premium sans exposer les secrets.",
    "superadmin.body": "Cette surface est réservée à notre équipe. Elle doit vivre derrière une authentification séparée avec MFA, audit log et rôles internes. Le frontend ne contient jamais les secrets Stripe ni la clé privée Ed25519.",
    "superadmin.nav_aria": "Navigation Superadmin",
    "superadmin.tab.overview": "Vue globale",
    "superadmin.tab.licenses": "Licences",
    "superadmin.tab.stripe": "Stripe",
    "superadmin.tab.security": "Sécurité",
    "superadmin.kpi.orgs": "Organisations",
    "superadmin.kpi.orgs_note": "clients Premium",
    "superadmin.kpi.seats": "Postes actifs",
    "superadmin.kpi.seats_note": "sur 5 600 achetés",
    "superadmin.kpi.mrr": "MRR estimé",
    "superadmin.kpi.mrr_note": "plan Premium unique",
    "superadmin.kpi.risk": "Alertes admin",
    "superadmin.kpi.risk_note": "à traiter",
    "superadmin.bootstrap.title": "Bootstrap sécurisé du premier superadmin",
    "superadmin.bootstrap.body": "Au premier déploiement, si aucun compte admin n'existe, le premier compte peut devenir superadmin uniquement avec un token de bootstrap serveur à usage unique. Le token expire, l'action est auditée, MFA est imposé, puis le bootstrap est désactivé définitivement.",
    "superadmin.bootstrap.step1": "Déployer avec `SUPERADMIN_BOOTSTRAP_TOKEN_HASH` côté serveur.",
    "superadmin.bootstrap.step2": "Créer le premier compte via `/setup` en HTTPS.",
    "superadmin.bootstrap.step3": "Vérifier le token, hasher le mot de passe, imposer MFA.",
    "superadmin.bootstrap.step4": "Créer un audit log et supprimer le mode bootstrap.",
    "superadmin.actions.title": "Actions sensibles",
    "superadmin.actions.revoke": "Révoquer une licence",
    "superadmin.actions.resign": "Régénérer entitlement",
    "superadmin.actions.release": "Publier release stable",
    "superadmin.actions.audit": "Exporter audit log",
    "superadmin.licenses.title": "Licences et organisations",
    "superadmin.status.active": "Actif",
    "superadmin.status.watch": "Surveillance",
    "superadmin.status.pending": "Paiement attendu",
    "superadmin.stripe.title": "Stripe et facturation",
    "superadmin.event.license_created": "licence créée",
    "superadmin.event.requires_action": "action requise",
    "superadmin.event.seats_updated": "postes mis à jour",
    "superadmin.security.title": "Garde-fous obligatoires",
    "superadmin.security.mfa": "MFA obligatoire pour tous les admins internes.",
    "superadmin.security.roles": "Rôles séparés : support, billing, release manager, superadmin.",
    "superadmin.security.keys": "Clé privée Ed25519 stockée hors frontend, idéalement KMS/HSM.",
    "superadmin.security.audit": "Audit log append-only pour chaque action sensible.",
    "superadmin.security.rate": "Rate limit et alertes sur login, reset MFA et révocation.",
  },
  en: {
    "nav.superadmin": "Superadmin",
    "superadmin.eyebrow": "NovaSentinel internal",
    "superadmin.title": "Superadmin dashboard to run Premium without exposing secrets.",
    "superadmin.body": "This surface is reserved for our team. It must sit behind separate authentication with MFA, audit logs, and internal roles. The frontend never contains Stripe secrets or the Ed25519 private key.",
    "superadmin.nav_aria": "Superadmin navigation",
    "superadmin.tab.overview": "Overview",
    "superadmin.tab.licenses": "Licenses",
    "superadmin.tab.stripe": "Stripe",
    "superadmin.tab.security": "Security",
    "superadmin.kpi.orgs": "Organizations",
    "superadmin.kpi.orgs_note": "Premium customers",
    "superadmin.kpi.seats": "Active seats",
    "superadmin.kpi.seats_note": "of 5,600 purchased",
    "superadmin.kpi.mrr": "Estimated MRR",
    "superadmin.kpi.mrr_note": "single Premium plan",
    "superadmin.kpi.risk": "Admin alerts",
    "superadmin.kpi.risk_note": "to handle",
    "superadmin.bootstrap.title": "Secure bootstrap for the first superadmin",
    "superadmin.bootstrap.body": "On first deployment, if no admin account exists, the first account may become superadmin only with a one-time server-side bootstrap token. The token expires, the action is audited, MFA is required, then bootstrap is permanently disabled.",
    "superadmin.bootstrap.step1": "Deploy with `SUPERADMIN_BOOTSTRAP_TOKEN_HASH` server-side.",
    "superadmin.bootstrap.step2": "Create the first account through `/setup` over HTTPS.",
    "superadmin.bootstrap.step3": "Verify the token, hash the password, require MFA.",
    "superadmin.bootstrap.step4": "Create an audit log and remove bootstrap mode.",
    "superadmin.actions.title": "Sensitive actions",
    "superadmin.actions.revoke": "Revoke license",
    "superadmin.actions.resign": "Regenerate entitlement",
    "superadmin.actions.release": "Publish stable release",
    "superadmin.actions.audit": "Export audit log",
    "superadmin.licenses.title": "Licenses and organizations",
    "superadmin.status.active": "Active",
    "superadmin.status.watch": "Watch",
    "superadmin.status.pending": "Payment pending",
    "superadmin.stripe.title": "Stripe and billing",
    "superadmin.event.license_created": "license created",
    "superadmin.event.requires_action": "action required",
    "superadmin.event.seats_updated": "seats updated",
    "superadmin.security.title": "Required guardrails",
    "superadmin.security.mfa": "MFA required for every internal admin.",
    "superadmin.security.roles": "Separate roles: support, billing, release manager, superadmin.",
    "superadmin.security.keys": "Ed25519 private key stored outside the frontend, ideally KMS/HSM.",
    "superadmin.security.audit": "Append-only audit log for every sensitive action.",
    "superadmin.security.rate": "Rate limits and alerts on login, MFA reset, and revocation.",
  },
};

["es", "de", "it", "pt", "ar"].forEach((language) => {
  superadminTranslations[language] = { ...superadminTranslations.en };
});

Object.assign(superadminTranslations.es, {
  "superadmin.eyebrow": "Interno NovaSentinel",
  "superadmin.title": "Dashboard Superadmin para gestionar Premium sin exponer secretos.",
  "superadmin.body": "Esta superficie está reservada a nuestro equipo. Debe estar detrás de una autenticación separada con MFA, audit log y roles internos. El frontend nunca contiene secretos Stripe ni la clave privada Ed25519.",
  "superadmin.nav_aria": "Navegación Superadmin",
  "superadmin.tab.overview": "Vista global",
  "superadmin.tab.licenses": "Licencias",
  "superadmin.tab.security": "Seguridad",
  "superadmin.kpi.orgs": "Organizaciones",
  "superadmin.kpi.orgs_note": "clientes Premium",
  "superadmin.kpi.seats": "Puestos activos",
  "superadmin.kpi.seats_note": "de 5 600 comprados",
  "superadmin.kpi.mrr": "MRR estimado",
  "superadmin.kpi.mrr_note": "plan Premium único",
  "superadmin.kpi.risk": "Alertas admin",
  "superadmin.kpi.risk_note": "por tratar",
  "superadmin.bootstrap.title": "Bootstrap seguro del primer superadmin",
  "superadmin.bootstrap.body": "En el primer despliegue, si no existe ninguna cuenta admin, la primera cuenta puede convertirse en superadmin únicamente con un token de bootstrap servidor de un solo uso. El token expira, la acción se audita, se exige MFA y luego el bootstrap se desactiva definitivamente.",
  "superadmin.bootstrap.step1": "Desplegar con `SUPERADMIN_BOOTSTRAP_TOKEN_HASH` en el servidor.",
  "superadmin.bootstrap.step2": "Crear la primera cuenta mediante `/setup` en HTTPS.",
  "superadmin.bootstrap.step3": "Verificar el token, hashear la contraseña, exigir MFA.",
  "superadmin.bootstrap.step4": "Crear un audit log y eliminar el modo bootstrap.",
  "superadmin.actions.title": "Acciones sensibles",
  "superadmin.actions.revoke": "Revocar licencia",
  "superadmin.actions.resign": "Regenerar entitlement",
  "superadmin.actions.release": "Publicar release estable",
  "superadmin.actions.audit": "Exportar audit log",
  "superadmin.licenses.title": "Licencias y organizaciones",
  "superadmin.status.active": "Activo",
  "superadmin.status.watch": "Vigilancia",
  "superadmin.status.pending": "Pago pendiente",
  "superadmin.stripe.title": "Stripe y facturación",
  "superadmin.event.license_created": "licencia creada",
  "superadmin.event.requires_action": "acción requerida",
  "superadmin.event.seats_updated": "puestos actualizados",
  "superadmin.security.title": "Guardrails obligatorios",
  "superadmin.security.mfa": "MFA obligatorio para todos los admins internos.",
  "superadmin.security.roles": "Roles separados: soporte, billing, release manager, superadmin.",
  "superadmin.security.keys": "Clave privada Ed25519 almacenada fuera del frontend, idealmente KMS/HSM.",
  "superadmin.security.audit": "Audit log append-only para cada acción sensible.",
  "superadmin.security.rate": "Rate limit y alertas en login, reset MFA y revocación.",
});

Object.assign(superadminTranslations.de, {
  "superadmin.eyebrow": "NovaSentinel intern",
  "superadmin.title": "Superadmin-Dashboard zur Steuerung von Premium ohne Offenlegung von Geheimnissen.",
  "superadmin.body": "Diese Oberfläche ist unserem Team vorbehalten. Sie muss hinter separater Authentifizierung mit MFA, Audit-Log und internen Rollen liegen. Das Frontend enthält niemals Stripe-Secrets oder den privaten Ed25519-Schlüssel.",
  "superadmin.nav_aria": "Superadmin-Navigation",
  "superadmin.tab.overview": "Übersicht",
  "superadmin.tab.licenses": "Lizenzen",
  "superadmin.tab.security": "Sicherheit",
  "superadmin.kpi.orgs": "Organisationen",
  "superadmin.kpi.orgs_note": "Premium-Kunden",
  "superadmin.kpi.seats": "Aktive Plätze",
  "superadmin.kpi.seats_note": "von 5.600 gekauft",
  "superadmin.kpi.mrr": "Geschätzter MRR",
  "superadmin.kpi.mrr_note": "einziger Premium-Plan",
  "superadmin.kpi.risk": "Admin-Warnungen",
  "superadmin.kpi.risk_note": "zu bearbeiten",
  "superadmin.bootstrap.title": "Sicherer Bootstrap des ersten Superadmins",
  "superadmin.bootstrap.body": "Beim ersten Deployment kann das erste Konto nur dann Superadmin werden, wenn noch kein Admin existiert und ein einmaliger serverseitiger Bootstrap-Token vorliegt. Der Token läuft ab, die Aktion wird auditiert, MFA wird erzwungen und Bootstrap anschließend endgültig deaktiviert.",
  "superadmin.bootstrap.step1": "Mit `SUPERADMIN_BOOTSTRAP_TOKEN_HASH` serverseitig deployen.",
  "superadmin.bootstrap.step2": "Das erste Konto über `/setup` per HTTPS erstellen.",
  "superadmin.bootstrap.step3": "Token prüfen, Passwort hashen, MFA erzwingen.",
  "superadmin.bootstrap.step4": "Audit-Log erzeugen und Bootstrap-Modus entfernen.",
  "superadmin.actions.title": "Sensible Aktionen",
  "superadmin.actions.revoke": "Lizenz widerrufen",
  "superadmin.actions.resign": "Entitlement neu erzeugen",
  "superadmin.actions.release": "Stable Release veröffentlichen",
  "superadmin.actions.audit": "Audit-Log exportieren",
  "superadmin.licenses.title": "Lizenzen und Organisationen",
  "superadmin.status.active": "Aktiv",
  "superadmin.status.watch": "Überwachung",
  "superadmin.status.pending": "Zahlung ausstehend",
  "superadmin.stripe.title": "Stripe und Abrechnung",
  "superadmin.event.license_created": "Lizenz erstellt",
  "superadmin.event.requires_action": "Aktion erforderlich",
  "superadmin.event.seats_updated": "Plätze aktualisiert",
  "superadmin.security.title": "Pflicht-Leitplanken",
  "superadmin.security.mfa": "MFA ist für alle internen Admins verpflichtend.",
  "superadmin.security.roles": "Getrennte Rollen: Support, Billing, Release Manager, Superadmin.",
  "superadmin.security.keys": "Privater Ed25519-Schlüssel außerhalb des Frontends, idealerweise KMS/HSM.",
  "superadmin.security.audit": "Append-only Audit-Log für jede sensible Aktion.",
  "superadmin.security.rate": "Rate Limits und Warnungen für Login, MFA-Reset und Widerruf.",
});

Object.assign(superadminTranslations.it, {
  "superadmin.eyebrow": "Interno NovaSentinel",
  "superadmin.title": "Dashboard Superadmin per gestire Premium senza esporre segreti.",
  "superadmin.body": "Questa superficie è riservata al nostro team. Deve stare dietro un'autenticazione separata con MFA, audit log e ruoli interni. Il frontend non contiene mai segreti Stripe né la chiave privata Ed25519.",
  "superadmin.nav_aria": "Navigazione Superadmin",
  "superadmin.tab.overview": "Vista globale",
  "superadmin.tab.licenses": "Licenze",
  "superadmin.tab.security": "Sicurezza",
  "superadmin.kpi.orgs": "Organizzazioni",
  "superadmin.kpi.orgs_note": "clienti Premium",
  "superadmin.kpi.seats": "Postazioni attive",
  "superadmin.kpi.seats_note": "su 5.600 acquistate",
  "superadmin.kpi.mrr": "MRR stimato",
  "superadmin.kpi.mrr_note": "piano Premium unico",
  "superadmin.kpi.risk": "Avvisi admin",
  "superadmin.kpi.risk_note": "da gestire",
  "superadmin.bootstrap.title": "Bootstrap sicuro del primo superadmin",
  "superadmin.bootstrap.body": "Al primo deployment, se non esiste alcun account admin, il primo account può diventare superadmin solo con un token di bootstrap server monouso. Il token scade, l'azione viene auditata, MFA è obbligatoria e poi il bootstrap viene disattivato definitivamente.",
  "superadmin.bootstrap.step1": "Distribuire con `SUPERADMIN_BOOTSTRAP_TOKEN_HASH` lato server.",
  "superadmin.bootstrap.step2": "Creare il primo account tramite `/setup` in HTTPS.",
  "superadmin.bootstrap.step3": "Verificare il token, hashare la password, imporre MFA.",
  "superadmin.bootstrap.step4": "Creare un audit log e rimuovere la modalità bootstrap.",
  "superadmin.actions.title": "Azioni sensibili",
  "superadmin.actions.revoke": "Revoca licenza",
  "superadmin.actions.resign": "Rigenera entitlement",
  "superadmin.actions.release": "Pubblica release stable",
  "superadmin.actions.audit": "Esporta audit log",
  "superadmin.licenses.title": "Licenze e organizzazioni",
  "superadmin.status.active": "Attivo",
  "superadmin.status.watch": "Sorveglianza",
  "superadmin.status.pending": "Pagamento atteso",
  "superadmin.stripe.title": "Stripe e fatturazione",
  "superadmin.event.license_created": "licenza creata",
  "superadmin.event.requires_action": "azione richiesta",
  "superadmin.event.seats_updated": "postazioni aggiornate",
  "superadmin.security.title": "Garanzie obbligatorie",
  "superadmin.security.mfa": "MFA obbligatoria per tutti gli admin interni.",
  "superadmin.security.roles": "Ruoli separati: support, billing, release manager, superadmin.",
  "superadmin.security.keys": "Chiave privata Ed25519 fuori dal frontend, idealmente KMS/HSM.",
  "superadmin.security.audit": "Audit log append-only per ogni azione sensibile.",
  "superadmin.security.rate": "Rate limit e avvisi su login, reset MFA e revoca.",
});

Object.assign(superadminTranslations.pt, {
  "superadmin.eyebrow": "Interno NovaSentinel",
  "superadmin.title": "Dashboard Superadmin para gerir Premium sem expor segredos.",
  "superadmin.body": "Esta superfície é reservada à nossa equipa. Deve ficar atrás de autenticação separada com MFA, audit log e papéis internos. O frontend nunca contém segredos Stripe nem a chave privada Ed25519.",
  "superadmin.nav_aria": "Navegação Superadmin",
  "superadmin.tab.overview": "Visão global",
  "superadmin.tab.licenses": "Licenças",
  "superadmin.tab.security": "Segurança",
  "superadmin.kpi.orgs": "Organizações",
  "superadmin.kpi.orgs_note": "clientes Premium",
  "superadmin.kpi.seats": "Postos ativos",
  "superadmin.kpi.seats_note": "de 5 600 comprados",
  "superadmin.kpi.mrr": "MRR estimado",
  "superadmin.kpi.mrr_note": "plano Premium único",
  "superadmin.kpi.risk": "Alertas admin",
  "superadmin.kpi.risk_note": "a tratar",
  "superadmin.bootstrap.title": "Bootstrap seguro do primeiro superadmin",
  "superadmin.bootstrap.body": "No primeiro deployment, se não existir nenhuma conta admin, a primeira conta pode tornar-se superadmin apenas com um token de bootstrap servidor de uso único. O token expira, a ação é auditada, MFA é obrigatório e depois o bootstrap é desativado definitivamente.",
  "superadmin.bootstrap.step1": "Fazer deploy com `SUPERADMIN_BOOTSTRAP_TOKEN_HASH` no servidor.",
  "superadmin.bootstrap.step2": "Criar a primeira conta via `/setup` em HTTPS.",
  "superadmin.bootstrap.step3": "Verificar o token, gerar hash da palavra-passe, impor MFA.",
  "superadmin.bootstrap.step4": "Criar audit log e remover o modo bootstrap.",
  "superadmin.actions.title": "Ações sensíveis",
  "superadmin.actions.revoke": "Revogar licença",
  "superadmin.actions.resign": "Regenerar entitlement",
  "superadmin.actions.release": "Publicar release stable",
  "superadmin.actions.audit": "Exportar audit log",
  "superadmin.licenses.title": "Licenças e organizações",
  "superadmin.status.active": "Ativo",
  "superadmin.status.watch": "Vigilância",
  "superadmin.status.pending": "Pagamento pendente",
  "superadmin.stripe.title": "Stripe e faturação",
  "superadmin.event.license_created": "licença criada",
  "superadmin.event.requires_action": "ação necessária",
  "superadmin.event.seats_updated": "postos atualizados",
  "superadmin.security.title": "Proteções obrigatórias",
  "superadmin.security.mfa": "MFA obrigatório para todos os admins internos.",
  "superadmin.security.roles": "Papéis separados: suporte, billing, release manager, superadmin.",
  "superadmin.security.keys": "Chave privada Ed25519 fora do frontend, idealmente KMS/HSM.",
  "superadmin.security.audit": "Audit log append-only para cada ação sensível.",
  "superadmin.security.rate": "Rate limit e alertas em login, reset MFA e revogação.",
});

Object.assign(superadminTranslations.ar, {
  "nav.superadmin": "Superadmin",
  "superadmin.eyebrow": "داخلي NovaSentinel",
  "superadmin.title": "لوحة Superadmin لإدارة Premium دون كشف الأسرار.",
  "superadmin.body": "هذه الواجهة مخصصة لفريقنا فقط. يجب أن تكون خلف مصادقة منفصلة مع MFA وسجل تدقيق وأدوار داخلية. الواجهة الأمامية لا تحتوي أبدا على أسرار Stripe أو مفتاح Ed25519 الخاص.",
  "superadmin.nav_aria": "تنقل Superadmin",
  "superadmin.tab.overview": "نظرة عامة",
  "superadmin.tab.licenses": "التراخيص",
  "superadmin.tab.stripe": "Stripe",
  "superadmin.tab.security": "الأمان",
  "superadmin.kpi.orgs": "المؤسسات",
  "superadmin.kpi.orgs_note": "عملاء Premium",
  "superadmin.kpi.seats": "الأجهزة النشطة",
  "superadmin.kpi.seats_note": "من 5,600 مشتراة",
  "superadmin.kpi.mrr": "MRR تقديري",
  "superadmin.kpi.mrr_note": "خطة Premium واحدة",
  "superadmin.kpi.risk": "تنبيهات admin",
  "superadmin.kpi.risk_note": "قيد المعالجة",
  "superadmin.bootstrap.title": "Bootstrap آمن لأول superadmin",
  "superadmin.bootstrap.body": "عند أول نشر، إذا لم يوجد أي حساب admin، يمكن للحساب الأول أن يصبح superadmin فقط مع token bootstrap من الخادم لمرة واحدة. ينتهي token، تسجل العملية في audit log، يفرض MFA ثم يتم تعطيل bootstrap نهائيا.",
  "superadmin.bootstrap.step1": "النشر مع `SUPERADMIN_BOOTSTRAP_TOKEN_HASH` على الخادم.",
  "superadmin.bootstrap.step2": "إنشاء أول حساب عبر `/setup` باستخدام HTTPS.",
  "superadmin.bootstrap.step3": "التحقق من token، تجزئة كلمة المرور، فرض MFA.",
  "superadmin.bootstrap.step4": "إنشاء audit log وإزالة وضع bootstrap.",
  "superadmin.actions.title": "إجراءات حساسة",
  "superadmin.actions.revoke": "إلغاء ترخيص",
  "superadmin.actions.resign": "إعادة إنشاء entitlement",
  "superadmin.actions.release": "نشر release stable",
  "superadmin.actions.audit": "تصدير audit log",
  "superadmin.licenses.title": "التراخيص والمؤسسات",
  "superadmin.status.active": "نشط",
  "superadmin.status.watch": "مراقبة",
  "superadmin.status.pending": "دفع منتظر",
  "superadmin.stripe.title": "Stripe والفوترة",
  "superadmin.event.license_created": "تم إنشاء الترخيص",
  "superadmin.event.requires_action": "إجراء مطلوب",
  "superadmin.event.seats_updated": "تم تحديث الأجهزة",
  "superadmin.security.title": "ضوابط إلزامية",
  "superadmin.security.mfa": "MFA إلزامي لكل admins الداخليين.",
  "superadmin.security.roles": "أدوار منفصلة: support و billing و release manager و superadmin.",
  "superadmin.security.keys": "مفتاح Ed25519 الخاص خارج frontend، ويفضل KMS/HSM.",
  "superadmin.security.audit": "Audit log append-only لكل إجراء حساس.",
  "superadmin.security.rate": "Rate limit وتنبيهات على login و reset MFA والإلغاء.",
});

Object.entries(superadminTranslations).forEach(([language, values]) => {
  translations[language] = { ...translations[language], ...values };
});

Object.assign(translations.fr, {
  "meta.description": "NovaSentinel Premium : défense Windows complémentaire, licences professionnelles, réputation hash, règles signées et Admin Console téléchargeable.",
  "nav.download": "Télécharger",
  "nav.premium": "Premium",
  "nav.buy": "Acheter",
  "nav.admin": "Dashboard",
  "nav.login": "Login",
  "nav.security": "Sécurité",
  "language.label": "Langue",
  "hero.eyebrow": "Défense Windows complémentaire",
  "hero.body": "Une application de protection explicable pour Windows, avec services Premium hébergés par NovaSentinel : licences, mises à jour signées, réputation hash et distribution professionnelle.",
  "download.title": "Télécharger NovaSentinel",
  "download.body": "Version Windows avec activation Premium optionnelle",
  "download.button": "Download",
  "trust.one.title": "Pas un EDR",
  "trust.one.body": "Pas de promesse kernel ou mini-filter.",
  "trust.two.title": "Hash first",
  "trust.two.body": "Pas d'upload de fichiers par défaut.",
  "trust.three.title": "Clé signée",
  "trust.three.body": "Droits Premium vérifiés localement.",
  "trust.four.title": "Admin local",
  "trust.four.body": "Le parc client reste chez le client.",
  "premium.eyebrow": "Ce que nous hébergeons",
  "premium.title": "Premium ajoute des services professionnels, pas un faux moteur antivirus.",
  "premium.body": "NovaSentinel reste une défense complémentaire. Le cloud NovaSentinel sert aux licences, règles signées, réputation par hash, mises à jour, achat et distribution.",
  "feature.rules.title": "Règles et IOC signés",
  "feature.rules.body": "Base de hashs/signatures, seuils heuristiques enrichis et listes d'IOC distribués en packs signés.",
  "feature.cloud.title": "Réputation cloud",
  "feature.cloud.body": "Vérification des hashs inconnus, score serveur privé, cache local et mode confidentialité.",
  "feature.forensics.title": "Forensics Pro",
  "feature.forensics.body": "Rapports PDF/HTML, timeline d'incident, exports JSON/CSV et preuves enrichies.",
  "feature.distribution.title": "Distribution pro",
  "feature.distribution.body": "Auto-update de l'application, canal stable/beta, documentation pro et support prioritaire.",
  "buy.eyebrow": "Achat de clé",
  "buy.title": "Choisissez le nombre de postes et générez une clé Premium.",
  "buy.body": "Paiement prévu via Stripe Checkout. En production, le backend crée la licence seulement après webhook Stripe confirmé, puis signe les entitlements.",
  "form.org": "Organisation",
  "form.email": "Email responsable",
  "form.plan": "Plan",
  "form.plan_body": "Toutes les options Premium, facturées selon le nombre de postes.",
  "form.seats": "Nombre de postes",
  "form.submit": "Continuer avec Stripe",
  "summary.title": "Résumé",
  "summary.plan": "Plan",
  "summary.seats": "Postes",
  "summary.price": "Total mensuel",
  "summary.pending": "Clé générée après validation achat",
  "summary.note": "Stripe Checkout gère le paiement. La clé organisation est créée côté serveur après confirmation.",
  "checkout.created": "Session Stripe créée",
  "checkout.issued": "clé émise après webhook",
  "admin.eyebrow": "Pour responsables de parc",
  "admin.title": "NovaSentinel Admin Console sera téléchargeable.",
  "admin.body": "Nous hébergeons l'achat, les licences, les signatures et les mises à jour. L'Admin Console se télécharge côté client pour préparer les déploiements de masse, les clés Premium et les paquets de préconfiguration.",
  "admin.download": "Télécharger NovaSentinel",
  "admin.prepare": "Préparer Admin Console",
  "admin.integration": "Intégration prévue",
  "admin.item1": "Import de la clé organisation achetée.",
  "admin.item2": "Génération de scripts GPO, Intune, RMM et PowerShell.",
  "admin.item3": "Paquets JSON de préconfiguration et modèle CSV licences.",
  "admin.item4": "Synchronisation optionnelle avec l'API licence NovaSentinel.",
  "admin.entitlement": "Aperçu entitlement",
  "security.eyebrow": "Architecture sécurisée",
  "security.title": "Le secret reste côté NovaSentinel. L'app ne vérifie que des preuves signées.",
  "security.step1": "Achat et création de licence sur notre site.",
  "security.step2": "Activation par clé client ou clé organisation.",
  "security.step3": "Serveur NovaSentinel retourne un entitlement Ed25519 signé.",
  "security.step4": "L'app déverrouille seulement les droits signés et non expirés.",
  "footer.buy": "Acheter une clé",
  "footer.admin": "Admin Console",
  "footer.login": "Login",
  "footer.download": "Download",
});

const form = document.querySelector("#purchaseForm");
const licenseResult = document.querySelector("#licenseResult");
const adminSnippet = document.querySelector("#adminSnippet");
const languageSelect = document.querySelector("#languageSelect");
const superadminTabs = document.querySelectorAll(".superadmin-tab");
const superadminPanels = document.querySelectorAll(".superadmin-panel");
let currentLanguage = normalizeLanguage(localStorage.getItem(languageStorageKey) || navigator.language);

function normalizeLanguage(language) {
  const code = String(language || "fr").toLowerCase().slice(0, 2);
  return Object.hasOwn(translations, code) ? code : "fr";
}

function t(key) {
  return translations[currentLanguage]?.[key] || translations.fr[key] || key;
}

function purchaseState() {
  const data = new FormData(form);
  const seats = Math.max(1, Number.parseInt(data.get("seats") || "1", 10));
  const org = String(data.get("org") || "Organisation").trim();
  const email = String(data.get("email") || "").trim();
  return { plan: "premium", seats, org, email };
}

function applyTranslations() {
  document.documentElement.lang = currentLanguage;
  document.documentElement.dir = currentLanguage === "ar" ? "rtl" : "ltr";
  document.querySelector("meta[name='description']").setAttribute("content", t("meta.description"));
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    node.textContent = t(node.dataset.i18n);
  });
  document.querySelectorAll("[data-i18n-attr]").forEach((node) => {
    node.dataset.i18nAttr.split(",").forEach((binding) => {
      const [attribute, key] = binding.split(":").map((value) => value.trim());
      if (attribute && key) {
        node.setAttribute(attribute, t(key));
      }
    });
  });
  languageSelect.value = currentLanguage;
  renderSummary();
}

function renderSummary() {
  const { seats } = purchaseState();
  document.querySelector("#summaryPlan").textContent = premiumPlan.label;
  document.querySelector("#summarySeats").textContent = String(seats);
  document.querySelector("#summaryPrice").textContent = `${seats * premiumPlan.monthly} EUR`;
  if (!licenseResult.querySelector("strong")) {
    licenseResult.innerHTML = "";
    const pending = document.createElement("span");
    pending.textContent = t("summary.pending");
    licenseResult.append(pending);
  }
  renderAdminSnippet();
}

function renderAdminSnippet(key = "LICENSE_KEY_AFTER_STRIPE_WEBHOOK") {
  const { seats, org } = purchaseState();
  const payload = {
    organization: org,
    plan: "premium",
    seat_limit: seats,
    license_key: key,
    admin_console: "downloadable",
    hosted_by_novasentinel: ["purchase", "license_api", "signed_entitlements", "updates", "hash_reputation"],
    payment_provider: "stripe",
    customer_local: ["deployment_scripts", "bulk_license_csv", "preconfiguration_json"],
  };
  adminSnippet.textContent = [
    "%ProgramData%\\NovaSentinel\\premium_deployment.json",
    JSON.stringify({ license_key: key }, null, 2),
    "",
    t("admin.entitlement"),
    JSON.stringify({ ...payload, features: premiumFeatures }, null, 2),
  ].join("\n");
}

function renderLicenseResult(key, email, seats) {
  licenseResult.innerHTML = "";
  const wrapper = document.createElement("div");
  const label = document.createElement("span");
  const strong = document.createElement("strong");
  const detail = document.createElement("small");
  label.textContent = t("checkout.created");
  strong.textContent = key;
  detail.textContent = `${premiumPlan.label} | ${seats} ${t("summary.seats").toLowerCase()} | ${email} | ${t("checkout.issued")}`;
  wrapper.append(label, strong, detail);
  licenseResult.append(wrapper);
}

async function postJson(path, payload) {
  const response = await fetch(path, {
    method: "POST",
    credentials: "same-origin",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(data.message || data.error || `HTTP ${response.status}`);
  }
  return data;
}

function renderCheckoutError(message) {
  licenseResult.innerHTML = "";
  const wrapper = document.createElement("div");
  const label = document.createElement("span");
  const detail = document.createElement("small");
  label.textContent = "Stripe";
  detail.textContent = message;
  wrapper.append(label, detail);
  licenseResult.append(wrapper);
}

languageSelect.addEventListener("change", () => {
  currentLanguage = normalizeLanguage(languageSelect.value);
  localStorage.setItem(languageStorageKey, currentLanguage);
  applyTranslations();
});

form.addEventListener("input", renderSummary);
form.addEventListener("change", renderSummary);
form.addEventListener("submit", async (event) => {
  event.preventDefault();
  const { org, email, seats } = purchaseState();
  try {
    const checkout = await postJson("/api/checkout/sessions", { org, email, seats });
    renderLicenseResult(checkout.id, email, seats);
    window.location.href = checkout.stripe_checkout_url;
  } catch (error) {
    renderCheckoutError(error.message);
    renderAdminSnippet();
  }
});

document.querySelector("#adminPreview").addEventListener("click", () => {
  document.querySelector("#admin-console").scrollIntoView({ behavior: "smooth", block: "start" });
  renderAdminSnippet(licenseResult.querySelector("strong")?.textContent || "LICENSE_KEY_AFTER_STRIPE_WEBHOOK");
});

superadminTabs.forEach((tab) => {
  tab.addEventListener("click", () => {
    const target = tab.dataset.panel;
    superadminTabs.forEach((item) => item.classList.toggle("active", item === tab));
    superadminPanels.forEach((panel) => panel.classList.toggle("active", panel.dataset.panel === target));
  });
});

applyTranslations();
